### ISSUE TITLE
System buttons alignment

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#101]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open yomikiru.
2. Open settings, cycle through themes and obsersve the top buttons.
3. Click on home icon and observe the top buttons.

### ✔️ Expected Behavior

Alignment / sticking with top bar.

### ❌ Actual Behavior

Misplaced alignment and glitching.

**Comment by mienaiyami** [comment]
I'm unable to reproduce this bug, have you tried restarting pc, it might be system related.

**Comment by mienaiyami** [comment]
Will be fixed in next version.

**Comment by mienaiyami** [comment]
The issue was not visible to me because of device pixel ratio, display scale on laptop screen is usually higher than 125%.
