### ISSUE TITLE
EPUB File Error

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#103]
### Setup or portable version of the app?

Portable

### [Open the epub file.](https://github.com/mienaiyami/yomikiru/files/11332223/Reverend_Insanity.zip)

- After unzipping, error is shown briefly in the above title topbar.
- Open devtools and see errors / warnings. There are total of 23.

https://user-images.githubusercontent.com/127277950/235055133-4fe191f5-054f-4535-bfe4-b3825cd36aee.mp4

### DevTools
![Error](https://user-images.githubusercontent.com/127277950/235055150-62cd263f-bbc3-4319-b42d-da006be42637.png)

### ✔️ Expected Behavior

- To not have any errors / warnings.

### ❌ Actual Behavior

- Has errors / warnings. Some epub is not loaded at all. Show only error.
- The epub file that has not loaded, only one error in dev tools.
![Error](https://user-images.githubusercontent.com/127277950/235059147-4f88b2fe-f878-4edd-9650-5c00814e13c4.png)

**Comment by mienaiyami** [comment]
Warning mean nothing and its mostly caused by framework.

> For epub files that are not displayed after unzipping, it only shows error in the top bar title.
After opening dev tools, it showed only one error.

I only tested on 6 epub files i had, please send file causing error for test.

There wont be any update for few days.
