### ISSUE TITLE
Zip / cbz has 0 and new line in side list

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#106]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Place a zip / cbz file inside the manga folder you want to read.
2. View side list.

https://user-images.githubusercontent.com/116664905/235125248-ba38013d-23a5-4479-adce-0f865bb64a37.mp4

### ✔️ Expected Behavior

![Expected](https://user-images.githubusercontent.com/116664905/235126441-70c2a594-97d5-4475-8744-35c5dd479d6b.png)

### ❌ Actual Behavior

![Actual](https://user-images.githubusercontent.com/116664905/235126522-9b5837c5-ec6e-4e5b-ab66-cdb6a8117c55.png)

**Comment by mienaiyami** [comment]
fixed but not released
