### ISSUE TITLE
Margin width option for EPUB

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#107]
### Description of the new feature / enhancement

Option to set margin width for epub files in reader settings.

https://user-images.githubusercontent.com/127277950/235130891-38f60885-d370-43a5-b4f4-390a94c38f9d.mp4

### Scenario when this would be used?

To set custom margins.

**Comment by mienaiyami** [comment]
That is size under reader setting.

**Comment by mienaiyami** [comment]
That is not possible, without causing unwanted side effects.
