### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#11]
I noticed the less memory usage in the update v2.3.3.

1. How many pages does the reader cache now? Or is the caching completely disabled?
2. The CPU usage remained the same. Is it possible to reduce the CPU usage?
3. Image formats supported by the application?

**Comment by mienaiyami** [comment]
- It only cache pages from currently opened folder, and then remove them from cache when you open another folder.
- Unfortunately, it's not possible to reduce CPU usage as it needs to render images. I'm still searching for a better solution for rendering images so it doesn't cause stuttering.
- currently only ```".jpg", ".jpeg", ".png", ".webp", ".svg", ".apng", ".gif", "avif"``` are supported. as they are natively supported in the framework I'm using. But I plan to add ```.cbz``` soon. 
If you want to request some format, I can try adding it if possible.
Close the issue if you don't have any more queries.
