### ISSUE TITLE
Author Name not appearing In EPUB side list

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#111]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open the EPUB File below.
2. See side list, it does not show author name.

### ✔️ Expected Behavior

To show author name.

### ❌ Actual Behavior

It does not show author name.

![2](https://user-images.githubusercontent.com/127277950/235280729-91299250-41d9-45ea-bc8f-542cea4e8498.png)

**Comment by mienaiyami** [comment]
No author specified in epub.

**Comment by mienaiyami** [comment]
Yes, turns out there are more than one place where author can be specified in epub file.
