### ISSUE TITLE
EPUB side list appears in full screen

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#113]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any epub file and enter full screen.
2. The side can be accessed in full screen.

https://user-images.githubusercontent.com/127277950/235285594-8335f8d0-15f5-4aac-813c-8bdf701fe495.mp4

### ✔️ Expected Behavior

To not be able to access side list in full screen.

### ❌ Actual Behavior

Side list can be accessed in full screen.

**Comment by mienaiyami** [comment]
I left this as a feature because chapters are usually small. Should i remove this?
