### ISSUE TITLE
Line Spacing em minimum limit

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#115]
### Description of the new feature / enhancement

Limiting the minimum line spacing to '1 em' as anything below it overlaps with the previous line.

https://user-images.githubusercontent.com/127277950/235287048-f745260b-b66a-425f-ae54-70b7c70d0de7.mp4

### Scenario when this would be used?

When using line spacing option.

**Comment by mienaiyami** [comment]
That is how it works. 
1em = 100% of Font Size
So If line spacing is 1em, it mean height of line will be equal to font size, meaning no gap between lines. On going below 1, line height get below font size.

**Comment by mienaiyami** [comment]
Oh, I just realized that i should have named it line height and not spacing in settings.
