### ISSUE TITLE
Top Title does not change after closing EPUB file

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#118]
### Setup or portable version of the app?

Portable

### Steps to reproduce

Top title of epub file name stays there even after clicking on home button or after opening another folder / zip / cbz, only after reloading the app, the top title changes to yomikiru.

https://user-images.githubusercontent.com/127277950/235296618-94f52849-738e-4c82-9d38-211f058b79d5.mp4

### ✔️ Expected Behavior

When home button is clikced, the title of the opened epub file to change to app name just like it does for zip / cbz / folder .

### ❌ Actual Behavior

When home button is clikced, the previously opened epub title stays there.

**Comment by mienaiyami** [comment]
Thanks for reporting all these issues.
