### ISSUE TITLE
Natural numbers reading progress indicator for EPUB files

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#119]
### Description of the new feature / enhancement

- Just like the app has an indicator in normal screen and full screen when reading manga, in the same way for EPUB reader too.
- A progress indicator for EPUB Reader in normal screen, full screen.
- An option to enable it in epub reader settings just like manga reader settings has.
- Nothing fancy / animation, but just a good simple natural numbers indicator ranging from 1% to 100% for the reading chapter.

### Normal Progress Indicator

![Normal Progress Indicator](https://user-images.githubusercontent.com/127277950/235461911-7b78a7c4-d572-4e94-9058-63df7469fcf4.png)

### Full Screen Progress Indicator

![Full Screen](https://user-images.githubusercontent.com/127277950/236731045-d5167d6f-1e5a-46f7-a0dc-8f7d979e18a3.png)

### Scenario when this would be used?

While reading EPUB to know the reading progress of the current reading chapter.

### Supporting information

Example -  1%, 2% _ _ _ _  14%, so on, 100%.
And not - 1%, 1.1, 1.5%, 1.9%, etc.

**Comment by mienaiyami** [comment]
Im confused with the use of shape as it wont look good in corner. It would be better if you show it with book open in full screen.
