### ISSUE TITLE
Both Scroll speeds in epub reader settings not working

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#122]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any EPUB.
2. Enter a custom scroll value in the Scroll A, Scroll B.
3. The custom value no matter what is entered, only one scroll size happens for both.

https://user-images.githubusercontent.com/127277950/235959433-15b8bae9-9759-4ce7-8279-d4a042a316b8.mp4

### ✔️ Expected Behavior

Entered scroll value to work.

### ❌ Actual Behavior

Entered scroll value does not work and only one scroll size happens for both no matter which value is entered into it.

**Comment by mienaiyami** [comment]
Its likely linked to scroll speed of manga reader. 
Sorry I will fix when I have time.
