### ISSUE TITLE
Table of contents chapter shows dots instead of underscore

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#126]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any epub file.
2. Go to the TOC chapter.
3. Hover over the dotted words, the dots change to underscore.

https://user-images.githubusercontent.com/127277950/236661200-64589d32-16a6-4da5-85c4-6266c855abc4.mp4

### ✔️ Expected Behavior

To show underscores.

### ❌ Actual Behavior

Shows dots.

**Comment by mienaiyami** [comment]
i added that because there will be no other way to identify URL from actual underlined text.
