### ISSUE TITLE
Accessing chapters using content does not work properly

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#128]
### Setup or portable version of the app?

Portable

### EPUB - [Grandmster of demonic v01](https://mega.nz/folder/IQEWiDRZ#IkR9fJiEoSRGcvVsASR99A)

1. Open this epub
2. Go to the contents
3. Click on chapter one, two, etc
4. See side list chapter column, the chpater name is not shown
5. Also, navigate to next / previous chapter, it goes to the starting page.
6. This only happens when the chapters are accessed through contents page.

https://user-images.githubusercontent.com/127277950/236689922-4b21b47c-47a0-44b5-ae31-8ae515a42fe4.mp4

### ✔️ Expected Behavior

To show the chapter name and to work when clicked on contents like it does for other epub files.

### ❌ Actual Behavior

Clicking on contents causes unexpected behavior. Can be seen in the above video.

**Comment by mienaiyami** [comment]
It is because of the chapter link value in content. It is not possible to fix without causing unwanted side effects.
If links are correct, then TOC updates as well.

**Comment by mienaiyami** [comment]
I don't have enough knowledge of epub files and how they work, it was first time i ever touched this topic.
According to how my app works, its very improbable that there is some way to do prevent this without causing side effects.
I will still check if there's some way.

**Comment by mienaiyami** [comment]
Ah, thanks. 
I have something in mind that might not fix the issue but might improve it a little. Even it epub is made poorly, it will help.

**Comment by mienaiyami** [comment]
Fixed it but might have unknown side effects. Please report.
Forgot to include it in latest version, will be available in v2.15.1.
