### ISSUE TITLE
Epub file loads all the chapters in a single page even when the checkbox is checked

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#129]
### Setup or portable version of the app?

Portable

### EPUB - [The Count of Monte Cristo](https://github.com/mienaiyami/yomikiru/files/11358300/The-Count-of-Monte-Cristo.zip)

1. Open this epub.
2. The entire epub file is loaded in one single page even when the checkbox is checked.
3. Also, accessing the chapters using content does not show the chapter's name in the side list.

https://user-images.githubusercontent.com/127277950/236691203-e01ec26a-ede8-433d-9c00-0810026f317f.mp4

### ✔️ Expected Behavior

To show the chapters in different pages like it does for other epub's.

### ❌ Actual Behavior

Shows all the chapters in a single page even when the checkbox is checked.

**Comment by mienaiyami** [comment]
This epub is badly created. 1-9chapters are inside one file, so there is no way to only load one chapter at a time. It is also the reason this file had so many errors in previous build
