### ISSUE TITLE
Temp Files are not being cleared on app exit

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#131]
### Setup or portable version of the app?

Portable

### Steps to reproduce

**Temp Files Directory - C:\Users\  Your Pc Username Here  \AppData\Local\Temp**

1. Open any zip, cbz, epub file in yomikiru.
2. After they are unzipped and loaded, open temp files directory.
3. You can see all the temporary files stored there with the names and extension of the zip, cbz, epub previously opened by the app.

### ✔️ Expected Behavior

- The temporary files should be deleted on app exit.

### ❌ Actual Behavior

- The temporary files are not being cleared even after closing the application.

**Comment by mienaiyami** [comment]
>I am using portable version, So the temp files should be stored in the portable directory.
And the temp files should be deleted from the portable directory on app exit.

I'm not sure if that's how it is supposed to work. Temp directory is managed by the system and is recommended for this kind of work. Though it is possible to make it that way but then I will hate to create different rules for portable and setup version.
As for the deleting, there might be some issue there, I'll check that.
