### ISSUE TITLE
UI Request

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#137]
### Description of the new feature / enhancement

When a zip/cbz file is opened, in the side list, it's chapter name does not have .zip/.cbz extension.
But the extension is also recorded in history chapter name. So, my proposed continue reading feature is,

https://github.com/mienaiyami/yomikiru/assets/127277950/8bf1911e-0f9e-4d1d-b0bc-15e503998769

![UI](https://github.com/mienaiyami/yomikiru/assets/127277950/c0f1f67e-4375-4d80-8a84-dfb6ddd6c945)

![UI](https://github.com/mienaiyami/yomikiru/assets/127277950/4b5e7db7-8094-4cc7-8616-03fd4b12cfe7)

### Supporting information

If you like the above UI, please implement this. This is the best I could think of. Please improvise it if you have something more neat in mind.

**Comment by mienaiyami** [comment]
Maybe its better to just remove page number from UI?

**Comment by mienaiyami** [comment]
> Are https://github.com/mienaiyami/yomikiru/issues/137#issuecomment-1551474701necessary?

They dont appear unless you hover over them for long enough and is practically unnoticeable (to me atleast), and they do have date and page info which some people might need.
