### ISSUE TITLE
Request for opacity bar for font color in epub and live preview of it

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#138]
### Description of the new feature / enhancement

Sometimes the white font color is too bright to read with black / grey background.
So an opacity bar to adjust the font opactiy and a live preview of it, so I can save at the color, opacity I like.
It doesn't need to save it automatically, only save it by clicking on the save and apply button.

### Scenario when this would be used?

To set the font color, opacity in epub.

### Supporting information

By live preview, I want to see the change happening to the epub font, so that I could choose a perfect font color, opacity settings while reading epub's. Just like how it is done for theme maker. It shows live preview.

Suppose in the app theme maker, while changing the background it shows live preview and if save is not clicked it is not saved.
The same way for epub reader settings as it is now, only an opacity bar for font color and live preview is need to be added.

**Comment by mienaiyami** [comment]
> why does the theme maker in app settings feel hard when changin colors

as you can see, they are reflected in real time while in case of reader settings you need to click save to apply any changes in color.
So live preview is cpu intensive, and more so in reader settings so i had to make a save button for it.

**Comment by mienaiyami** [comment]
UI will stop working for few seconds (over 10s easily).

**Comment by mienaiyami** [comment]
I can add opacity though.

**Comment by mienaiyami** [comment]
> [v2.8.0](https://github.com/mienaiyami/yomikiru/releases/tag/v2.8.0) supports it.

what are you refering to?

**Comment by mienaiyami** [comment]
No, even if its just one chapter it will still freeze.
