### ISSUE TITLE
Please look into the app's unzipper

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#139]
### 1. I checked with a 450 Mb zip file comparing winRAR and yomikiru.

WinRAR
-
- Time taken to unzip the above zip file = 5 seconds.

Yomikiru
-
- Time taken to unzip the above zip file = 11 seconds. (Unzipping takes 120% more time than winRAR)
- And extra 2 seconds to load it. (The loading is fast and perfectly normal)

EPUB Reader
-
- Time taken to unzip and load the above epub file = 2 seconds.

Yomikiru
-
- Time taken to unzip and load the above epub file = 8 seconds . (Unzipping and loading takes 300% more time than EPUBReader.)

### Supporting information

EPUB Reader
-
- Time take to unzip and load the above epub file = 1 Second.

Yomikiru
-
- Time taken to unzip and load the above epub file = 3 Seconds.

**Comment by mienaiyami** [comment]
So according to my test with 607mb zip,
| Method | Time(s) |
|--------|--------|
| WinRAR | 4.36 |
| File explorer | 12.83 |
| 7zip | 3.62 |
| Yomikiru | 5.24 | 

I tested multiple time, and personally I can't find an issue here. Yes, it is slower than WinRAR and 7zip.
And that little time might be from launching PowerShell in background as it is the unzipper used by the cross platform unzipping library I use. 

It is also registered under #90, and I haven't been able to reproduce it yet.

**Comment by mienaiyami** [comment]
> Time taken to unzip and load the above epub file = 8 seconds .

Its unfortunate but i dont know what is causing this and since unzipping is handled by something i didnt write, i cant control it (not that i could because its complex).
I have tried many other unzippers but i prefer this one as its easier to work with and theres almost no difference in speed.
