### ISSUE TITLE
The scrolling in epub feels hard

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#140]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any epub file with many chapters, as it will be more noticable.
2. Scroll up or down.
3. You can feel something hard while scrolling.
4. To make sure I checked with a 450 MB zip file that contains high quality manga images and the scrolling there feels very smooth, unlike in epub's.

### ✔️ Expected Behavior

The scrolling to feel smooth in epub's, for reference, like it feels in EPUBReader.

**Comment by mienaiyami** [comment]
> Yes. I do not feel any bump in #143, but for Epub's I can still clearly feel it sometimes.

Can you provide more info. Im unable to reproduce.

**Comment by mienaiyami** [comment]
> I think scroll a is not working. scrolll a causes bumpy mess. So do it with scroll b.

#153

**Comment by mienaiyami** [comment]
I tested on above file and found no stutter or bump. It might be a system lag.

**Comment by mienaiyami** [comment]
It might be like it because EPUBReader is for firefox and it have different engine and all other things than chromium. And even after that, big browsers like chrome and edge make many changes chromium. I cant do that.

**Comment by mienaiyami** [comment]
> My doubt.
Wouldn't using the mouse scrolling system (engine) of firefox solve this?

Its not scrolling but the whole engine itself. Also something like that isnt possible.
And as i said before, I have yet to reproduce this. Most of these are caused by system interference.
