### ISSUE TITLE
Images are not displaying for long manga, chapter titles

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#141]
### Setup or portable version of the app?

Setup

### Steps to reproduce

1. Replace the volume 1 name with it's japanese title or any long title.
2. Open the manga.
3. The images do not appear.

### ✔️ Expected Behavior

To show images like it normally does.

### ❌ Actual Behavior

It doesn't show images.

**Comment by mienaiyami** [comment]
Long name is not supported well by system.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/b1bf00a0-cbdc-44b3-973e-3f667c3921c8)

Even if you are able to extract it using other means, its not possible to view them on web using their actual name.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/7f511488-3088-4a06-8d46-a0dab3681fb1)
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/456fdabe-2de7-4758-96f7-c40f21fd80e8)

It might have been possible but as you can see here, images are name like this, which is too long for system.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/025c0339-f40e-478f-bb87-a2e05a4c3fb8)

**Comment by mienaiyami** [comment]
So i dont know it might be possible to fix with my current knowledge.
