### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#145]
### Setup or portable version of the app?

Portable

### Steps to reproduce

Assign custom shortcut keys in app settings.

### ✔️ Expected Behavior

For the shortcut keys to not revert to default keys when the app is reloaded or restarted.

### ❌ Actual Behavior

The shortcut keys revert to default keys when the app is reloaded or restarted.

**Comment by mienaiyami** [comment]
I forgot to include it in this version. Will be available in next.
