### ISSUE TITLE
Possible memory issue on app start

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#151]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. v2.11.3 takes 2 - 3 times more RAM than previous versions.
~~2. Reloading the app does not clear the memory as effectively as it did in previous versions.~~

### ✔️ Expected Behavior

To take the same memory as it did for previous versions when they were updated.

**Comment by mienaiyami** [comment]
It is not related to them at all, and I cant reproduce it yet. My ram usage is 70mb every time i launch. And there is a little increase in RAM usage because of #140, #143. Performance doesn't come for free, there is always RAM and CPU factors.

**Comment by mienaiyami** [comment]
Im not sure myself. It is not my area of expertise.

**Comment by mienaiyami** [comment]
Check if hardware acceleration affect.
