### ISSUE TITLE
Page Indicator

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#154]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any manga.
2. Type a value in page indicator.
3. Go to the next / previous chapter using side list / shortcut keys.
4. See page indication number.

- It does not happen in mouse scrolling, scrolling using keys, zen mode.
- This only happens when page number is typed in page indicator.

https://github.com/mienaiyami/yomikiru/assets/116664905/ee9a8570-ca9b-4191-9458-974219387355

### ✔️ Expected Behavior

To show page number 1 when accessing next / previous chapter.

### ❌ Actual Behavior

Shows the page number from the last left off chapter instead of 1.

**Comment by mienaiyami** [comment]
Unable to reproduce.

**Comment by mienaiyami** [comment]
Im unable to still reproduce it. But I have put measures to prevent it anyway.
