### ISSUE TITLE
 SmoothScrolling bug

### ISSUE THREAD

**Issue by jamesbondiknow** [mienaiyami/yomikiru#156]
### Setup or portable version of the app?

Setup

### Steps to reproduce

I've noticed that this only happens when I use the Up and Down Arrow keys, SmoothScrolling stops working if I press the "Settings" button then use the W and S keys first the Arrow keys, work just find until I change the the images size that causes it to reset back 
to being 
 a stuterring mess. If I don't mess with the Fit Options and just change it to "Next Chapter" or "Previous Chapter" it still works just fine with the Arrow keys.  Both of these are at a 5 scrolling speed.

### ✔️ Expected Behavior

https://github.com/mienaiyami/yomikiru/assets/57119993/f6816949-af14-44af-9333-407278dca81d

### ❌ Actual Behavior

https://github.com/mienaiyami/yomikiru/assets/57119993/0a435f2e-c13f-4534-b453-f8b4fd2bd08b

**Comment by mienaiyami** [comment]
Copy of #153

**Comment by jamesbondiknow** [comment]
apologizes I didn't know this was already reported

**Comment by mienaiyami** [comment]
Sorry for not releasing new update yet.
