### ISSUE TITLE
History is not saved on app exit

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#157]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any manga.
2. Go to any page other page 1.
3. Close the app.

- In the below video, I closed the app at page 49.
- Reopening the app, I clicked on the continue reading, it started at page 40 instead of page 49.

https://github.com/mienaiyami/yomikiru/assets/116664905/005a46cc-a8fb-43ad-9a67-9be311aec068

### ✔️ Expected Behavior

For the history to be saved when the app is closed.

### ❌ Actual Behavior

History is not saved when the app is closed.

**Comment by mienaiyami** [comment]
Ah forgot about that. After I added 2second delay in saving history to prevent corruption, I forgot to adjust for this.
