### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#16]
###  1. Confirmation Dialogue Box On application Exit.

- A confirmation dialogue box when trying to exit the application.
- Example - Shortcut keys dialogue box of your app when trying to assign the same 'key' to another function.

![image](https://user-images.githubusercontent.com/111482404/200979059-182490ac-708b-42e5-9e5d-14b236fa4b40.png)

### 2. Dialogue Box

- The above dialogue box in in light theme, even when my system theme is set to dark theme.
- The Manga Reader Application is also set to dark theme.

**Comment by mienaiyami** [comment]
>1. Confirmation Dialogue Box On application Exit.

You will be able to enable this from settings in next update.

>2. Dialogue Box

Unfortunately, there's nothing I can do about that, its windows default dialog. Try to copy/paste a file in file explorer, you will notice that the popup window is white even though dark theme is selected.
Of course, I can always make a custom dialogue box but at cost of extra ram.

**Comment by mienaiyami** [comment]
>trying to exit the application

means a lot, does it have to include alt+f4, closing from alt+tab window, closing from taskbar or just simply closing by clicking on "in app close button". Please specify and I will be adding that in next update.

**Comment by mienaiyami** [comment]
> If you can, please provide an option to enable/disable logs as to have more freedom to choose.

- As I have already told you, logger doesn't take any ram, its total size if 102KB. It only logs important things like error locally on your machine and I (or someone else other than you) can't access that.
- Its not as easy as adding enable/disable logs to settings. It is built in deep and if i were to implement it, it will take extra ram a this is starts on startup of application.

**Comment by mienaiyami** [comment]
It will be, I'm sorry, I'm very busy so I can't work on the app right now. I will, for now revert back my changes which i made in attempt to make it nonstuttering and publish update today.
