### ISSUE TITLE
Cases of page indicator stopping

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#161]
### Setup or portable version of the app?

Portable

### Case - 1
1. Open any manga.
2. Navigate using page indicator.
3. Now keep scrolling up / down.
4. It will stop counting or to be precise it hides the counting when the text cursor is focused in page indicator.

### Case - 2
1. Open any manga.
2. Navigate using page indicator.
3. Enter zen mode.
4. Sometimes, even when the page is on 1 after navigating, entering the zen mode shows the before navigation page number.

### Case - 1
- To not stop counting after navigation.
- When a number is entered, loose foucs on the page indicator after scrolling to that page, instead of text cursor focusing on it. 
- Just like when the text cursor loses focus after pressing enter to navigate.

### Case - 2
- To show the current navigated page number after entering zen mode and to not stop working.

### Case - 1
- Hides counting after navigation, if text cursor is focused in page indicator.

### Case - 2
- Sometimes, page indicator stops working for the present manga and any other manga opened.
- So it causes the history to stop working too.
- Either the app needs to be restarted or reloaded to make it work again.
- Or, should navigate again using the page indicator for it to work.

**Comment by mienaiyami** [comment]
> On the last page the page indicator does not show 51 and instead shows 50.

App take page number from a point in upper half of screen, so thats normal.
