### ISSUE TITLE
Lag while exiting full screen for a particular epub file

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#163]
### Setup or portable version of the app?

Portable

### Steps to reproduce

A couple issue I found while reading.

1. Open the epub files in the acutal behavior and expected behavior.
2. Enter and exit full screen.
3. The second epub file is causing lag while exiting full screen.

### ✔️ Expected Behavior

First EPUB - [Grandmster of demonic v01](https://mega.nz/folder/IQEWiDRZ#IkR9fJiEoSRGcvVsASR99A)

https://github.com/mienaiyami/yomikiru/assets/127277950/722c8f65-9170-41d7-b846-7779912bab71

### ❌ Actual Behavior

Second EPUB - [File causing the title behavior](https://www.mediafire.com/file/hzl4hfkzwpp8frt/Reverend_Insanity.epub/file)

https://github.com/mienaiyami/yomikiru/assets/127277950/dfefa032-6000-4e3d-bac4-808c81e1fe00

**Comment by mienaiyami** [comment]
Cant be fixed.
