### ISSUE TITLE
EPUB Reader settings UI

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#164]
### Description of the new feature / enhancement

Could you please include these in the next update.

1. Please move the " No Indent " box to font tab's last place. That is under " Word Spacing ".
2. Please remove the hyphenation box as there is no need for it. If you do not have any plan for this.

### Scenario when this would be used?

Colors and brightness options will be under style tab now. Now to change colors style tab will be used.
No indent and progress will be under font tab.

### Supporting information

To not get confused.

**Comment by mienaiyami** [comment]
> Please move the " Show Progress In Zen Mode" to font tab's last place. That is under " No Indent ".

does it count as font settings?
