### ISSUE TITLE
Anilist tracking.

### ISSUE THREAD

**Issue by toprak** [mienaiyami/yomikiru#167]
### Description of the new feature / enhancement

After reading chapter 1 of aot's it should make chapter 1 read.

**Comment by mienaiyami** [comment]
Actually, I also wanted to add anilist tracker for myself for a long time (similar to tachiyomi) but had been avoiding keeping the app offline. 
If there are users who want purely offline app then I can add option to block internet for it.
I will continue any bug fixes or enhancements after 10 June.

**Comment by toprak** [comment]
@omodia it does not matter is it offline or online, there are manga so it should track, like komga does okay?

**Comment by mienaiyami** [comment]
Added in v2.13.0
