### ISSUE TITLE
Page gap is shown rarely even when gap between pages is disabled

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#169]
### Setup or portable version of the app?

Portable

### Steps to reproduce

I found this by accident while reading normally and was confused whether I set a gap between pages.
I checked the reader settings and saw that I did not set any. That way I found this bug.
It took a lot of time for me in finding a way to reproduce this bug.

### File - [1 - 1.zip](https://github.com/mienaiyami/yomikiru/files/11627069/1.-.1.zip)

1. Extract and open the above 1-1 zip file.
2. Open 1-1.
3. Open reader settings and enable gap between rows.
4. After scrolling down at every gap, disable it.
5. If cannot find any gap, enable it again.

---
https://github.com/mienaiyami/yomikiru/assets/116664905/de580d74-ae2f-48f9-8675-48686c850d2d

### ✔️ Expected Behavior

To not show any page gap.

### ❌ Actual Behavior

Shows page gap very rarely.

---
### After finding the page gap, change fit options, the page gap disappears.
---

https://github.com/mienaiyami/yomikiru/assets/116664905/f697800a-dd60-4baf-8610-edf60949345f

**Comment by mienaiyami** [comment]
I have updated electron version so might fix this. As it is not reproducible, I will be closing it and #170.
