### ISSUE TITLE
Improper margin width

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#170]
### Setup or portable version of the app?

Portable

### Steps to reproduce

This might be related to #169.
Found this bug while trying to reproduce #169.

### File - [Chapter 110.zip](https://github.com/mienaiyami/yomikiru/files/11627185/Chapter.110.zip)
---
### Case - 1
1. Extract and open the above zip file.
2. Scroll to page 37.
3. Enable show gap between rows.
4. Keep an eye on the right edge of the page.
5. Disable gap between rows.
6. Improper margin width can be seen at right edge even when current page and previous page width is 850 px.

https://github.com/mienaiyami/yomikiru/assets/116664905/656175e0-c8b8-4f0b-890c-e7fc93c9b8fe

---
### Case - 2
1. Extract and open the above zip file.
2. Scroll to page 37.
3. Enable show gap between rows.
4. Keep an eye on all the four edges of the page.
5. Improper margin width can be seen even when in free size and also when max page width is enabled in 1:1 option.

https://github.com/mienaiyami/yomikiru/assets/116664905/3a01699e-2793-4b5e-8dd7-027a095ca194

### ✔️ Expected Behavior

To not show any improper margin width for both cases.

### ❌ Actual Behavior

Shows improper margin width for both cases.

**Comment by mienaiyami** [comment]
Such things are not something I can fix sadly. It is caused by browser rendering issues.
Same goes for #169. 
I will try to update chromium version next time, may or may not help.

Also in this issue, its possible that rightmost pixels are all black.

**Comment by mienaiyami** [comment]
> In Yomikiru, are all the images handled and rendered by chromium and electron, be it jpg, png and webp?

Yes, just chromium.

**Comment by mienaiyami** [comment]
https://github.com/mienaiyami/yomikiru/issues/169#issuecomment-1589317653
