### ISSUE TITLE
Auto Scroll Down and a shortcut key to enable / disable it

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#173]
### Description of the new feature / enhancement

Please add the option to auto scroll the current chapter in scroll speed (with keys) column.

### Scenario when this would be used?

To auto scroll through the current reading chapter in epub and comic.

### Supporting information

Please add an option to enable / disable auto scroll.
The auto scroll px value should be enterable / changeable even when the option is disabled.
Because if auto scroll is enabled it will scroll through automatically before entering the desired value without this.
The enterable scroll value in auto scroll is of px, the same as scroll speeds.

**Comment by mienaiyami** [comment]
You can use middle mouse button. With it you can choose direction as well as speed.
