### ISSUE TITLE
Previous / Next chapter navigation not working on clicking right / left side of the screen in full screen for epub's at 100%

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#174]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any epub.
2. Enter full screen.
3. Go to last (100%).
4. Click left / right side of page to go to previous / next chapter.
5. It's not working.
6. Exit full screen and go to 100%.
7. Now click left / right of page, it works now, but not in full screen.

### ✔️ Expected Behavior

To go to previous / next chapter when left / right side of the screen is clicked like it works for manga, and when epub is not in full screen.

### ❌ Actual Behavior

Navigation using mouse click on the left / right side of the screen does not work in full screen.

**Comment by mienaiyami** [comment]
Unable to reproduce.

**Comment by mienaiyami** [comment]
From my test it is still working. Is it only for this specific epub?
