### ISSUE TITLE
Epub Side list TOC scroll bar to follow the current chapter

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#177]
### Description of the new feature / enhancement

1. Please make the epub TOC scroll bar to follow the current reading chapter like it does for manga.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/e354d146-b45c-4e67-b766-32075a7cefff

---

https://github.com/mienaiyami/yomikiru/assets/127277950/3ebc18a2-625c-430c-a5b9-f083afbd6078

**Comment by mienaiyami** [comment]
Its kind of not possible, because every UI is hidden in zen mode. 
But I can make it focus on current chapter every time you exit zen mode.
