### ISSUE TITLE
Stuttering on large Images still present

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#18]
Until v2.3.5 I could see the stutter, but now the Stuttering has been fixed.

- Even while scrolling up or down very fast, there is no stutter now.
- Now I do not see any stutter except in large images of size (2000 x width).
- If you want to test it yourself, I can send the images to you.

By the way, what does scroll speed 1 and 2 do?

### Thank you for fixing the stuttering issue.

**Comment by mienaiyami** [comment]
Thank you for being patient for stuttering issue.
> If you want to test it yourself, I can send the images to you.

I tested with 4k images myself, so no need for that.
>By the way, what does scroll speed 1 and 2 do?

scroll 1 is w/s or arrow up/down (by default)
scroll 2 is space/ shift space (by default)

Now you can have 2 different scrolling speed on keypress.
Close issue if nothing to comment.

**Comment by mienaiyami** [comment]
Thats weird, because there is no stuttering for me now. Can you tell me your system spec, it might be the reason for stuttering. Or upload the folder whose video these are on https://github.com/alenwai/Stutter-Example, so I can test them on my system.

**Comment by mienaiyami** [comment]
Okay, so its stuttering for me as well. I will look into it. Sorry for your inconvenience

**Comment by mienaiyami** [comment]
Thanks for the suggestion, I will check it out.

**Comment by mienaiyami** [comment]
Thank you so much for providing these resources, I will try my best to fix it. Hopefully it is in this framework

**Comment by mienaiyami** [comment]
I'm very sorry, there might not be a solution for this, but I will keep trying.
As of now I recommend not using images with very high resolution (except its height) as you won't get greater quality unless your display is 4k and it will take lot of CPU usage to render and scale down to fit screen.
Sorry for not able to fix it. I'm only solo developers and I don't have any contacts with other developers.
