### ISSUE TITLE
Epub side list pinning and reader settings

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#186]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any epub.
2. Pin the side list.
3. Open the reader settings.
4. Click on any option in the reader settings or simply click on the arrow to collapse/uncollapse.

https://github.com/mienaiyami/yomikiru/assets/127277950/167d2a82-d0df-4f68-91db-ba256e97a541

### ✔️ Expected Behavior

When side list is pinned and accessing reader settigs, it should behave in the same way as when the side list is not pinned and accessing reader settings.

### ❌ Actual Behavior

Epub is progressing.

**Comment by mienaiyami** [comment]
To be honest, I have no clue why this is happening and when it started. I had already burned few hours in this before you created this issue and gave up . Theres also the issue that make reader scroll on resizing sidelist.

If you know the last version it was working right, please let me know.
The scale of this application had increased a lot from few months and it is getting harder to fix issues without proper info.
