### ISSUE TITLE
add use gpu to speed up 

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/yomikiru#189]
Hi, please add use GPU to speed up   very  slow to open PDF I think add GPU or use webview2 with great  or add some settings or fo speed up  but  grateful for add PDF very  high quality  job

**Comment by mienaiyami** [comment]
App use GPU by default unless "Hardware Acceleration" is disabled in settings.

**Comment by mienaiyami** [comment]
I use pdf.js by Mozilla and there's bo option to manually render using gpu.

>or use webview2

App already use chromium and i dont know if I can use webview2 with NodeJS as of now.

**Comment by mienaiyami** [comment]
If your CPU has iGPU, you might need to change graphics preference for Yomikiru in system setting to use dedicated GPU.
