### ISSUE TITLE
Theme maker

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#196]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Go to theme maker
2. Change button color to any other color
3. Change button hover over color to any other color
4. Save them

### ✔️ Expected Behavior

To change all button colors

### ❌ Actual Behavior

Some button colors are not changed. While some other are misbehaving.

Example,
- Reset button
- Link button
- Highlighted texts ( ctrl + shift + i)

**Comment by mienaiyami** [comment]
Thats for pointing out, it seems hover color is not correct for them.

> Highlighted texts ( ctrl + shift + i)

What are you referring to?

**Comment by mienaiyami** [comment]
It is linked to "Code BG Color", I don't see any issue related to it. Maybe its name need to be changed?
