### ISSUE TITLE
Opacity bar in theme maker

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#197]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Go to theme maker
2. Change the value of opacity bar
3. Click on save or save as new

---

https://github.com/mienaiyami/yomikiru/assets/116664905/f5bd8218-9bd3-4155-a6f6-5a427aa7ec87

### ✔️ Expected Behavior

Opacity bar value to not change when clicked on save.

### ❌ Actual Behavior

Opacity bar value increases by 1 when clicked on save.

**Comment by mienaiyami** [comment]
The way color is applied (hex color) make it impossible to get exact value in range of 1-100.

Hex color (#RRGGBBAA), here all RGB are in range of [0,255] but for "alpha/opacity" though it is saved as [0,255] is floating point value (0,1) so it can be like 0.564. And it makes no sense to make opacity range as 0-255 so actual value get lost in rounding.
