### ISSUE TITLE
epub navigation

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#202]
### Description of the new feature / enhancement

- If any epub is opened, it will be unzipped to the temp folder and then displayed in yomikiru.
- Since epub is the same as zip, cbz, 7z files. I mean archive.
- So large archives cause the reader to slow down which is normal and it is the same for large zip, 7z, cbz files.

---

### So I have an idea to solve this. I don't know if it is possible to do this.

1. Epub chapters will be unzipped and placed in a folder with epub title as the folder's name. (Same way as manga files)
2. Parent folder -> Epub files .xhtml
3. For epub side list, take the epub and chapter title from the folder name and chapter.xhml files respectively.
4. Same as manga side list. So no dependency on TOC.ncx, content.opf files.
5. As the epub side list and its navigation would work the same way as it does for manga sidelist, navigation.
6. If stylesheet is needed for the custom text, paragraph spacing, etc of the chapters then stylesheet.css will be in the epub folder alongside the .xhtml files or treat .css file in the epub folder as stylesheet, since there will only be one.
7. If this works, there will be no loading times, no uzipping times, no lag at all.
8. Please check.

---

### Drawback

1. Collapsible / Un-collapsible TOC would not work. But it is only one drawback and it does not matter.

---

### Scenario when this would be used?

- To read epub's lag free, unzipping times free.

---

### Supporting information

1. Basically the same navigation system as manga, but there will be a stylesheet.css (Only if needed).
2. The chapter will be directly inside the parent folder rather than sub-folders.
3. As for the image files in the epub, I extracted them to the epub folder and changed the respective image links to the local image links and it worked when I opened the .html file in browser (Even if the images do not work, its not a problem).

**Comment by mienaiyami** [comment]
I was already planning to make option to not temp files after app close so they can be opened again without big loading time.
In case of epubs, most of the loading time is used in just extracting and not loading the content.

This does sound like a better option in term of overall performance but at same time its a lot more complex.
First I will try the method i mentioned above as it sound easier to implement and works for all archives and pdf as well. If there is still a need for your method after this then I might consider.

**Comment by mienaiyami** [comment]
Added in 2.15.1 as test. 
Do you think there is a need for your way?

**Comment by mienaiyami** [comment]
> Also there would be no need for the temp and other files in this way.

It will though, since those new created files are kind of temp files. Also, it will be taking more than double the storage. 

> Even when a manga has 1000's of chapters, there is no effect on performance, because they are not in archive format.
I think the same will happen to epub's in this way.

Thats true.

**Comment by mienaiyami** [comment]
Maybe I didnt get what you mean.
Arent you saying that epub should be unzipped and kept in same folder permanently, and have its content arrange folder as chapters in manga? If so, wont there be extra space usage of more than the epub itself.

> If a stylesheet is needed to add custom line, paragraph spaces, etc.
> Then the stylesheet will be in the respective epub's folder, so there wouldn't need to be a temp file.

Usually theres one or two stylesheets and they apply to all chapters. But they do not contain just line, paragraph space, etc., there are many other styles. 

> Any unzipped archive would go back to its original size.

What does that mean?

**Comment by mienaiyami** [comment]
> * The user will unzip the epub themselves using winrar or 7zip.
> * They will then place both the stylesheets, .html / .xhtml / .mhtml files in a folder having the epub name.

I dont think its ideal for users to do that. As you just said, it is for epub with high chapter count.

Also in most cases one .xhtml file is not same as one chapter. A chapter can have more than one file and images as defined in content.opf and TOC



> * Yomikru doesn't need to do any complex process.
> * As in the above video, the user will unzip the text files, stylesheet and place it in a folder.
> * Yomikiru needs to be able to read that folder.

So this is not possible, unless Yomikiru itself make those folders with help of content.opf and TOC.ncx. Try looking at extract of different epubs.

Still the main issue will be order and content of chapter.
For example, 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/67e972ea-9fd1-462d-8772-11554ae3a80f) 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/f8676711-8be9-49c3-b874-b21d3faa0670)

![image](https://github.com/mienaiyami/yomikiru/assets/84740082/ae85f634-7e33-4675-926e-c6e640def5bf)

As you can see here, xhtml files dont really represent chapters. Real chapter files are in TOC and they internally import other .xhtml file which are outside of TOC (they are in content.opf and relationship if defined there).

**Comment by mienaiyami** [comment]
It turned out to be harder than expected. Everything is there to make it work but it require me to make a separate file as manga and epub have their own. Which I dont want to because then I will have same code everywhere.
But I was already planning to make something like this that works with .html or .txt or .md, so I will try to find some solution, but dont expect this feature anytime soon.

**Comment by mienaiyami** [comment]
> Do you mean the lag that occurs when resizing the side list?

No, i mean that lag will be there as long as there is high chapter count in sidelist, its same for manga's side list. 
The lag you see in that epub is because of side list and not the data in memory.

**Comment by mienaiyami** [comment]
> Or, are you talking about the reader lag? Yes, I have noticed it, compared to the version v2.12.3, the epub reader is laggy while going to another chapter in the present version.

Thats because of https://github.com/mienaiyami/yomikiru/issues/177#issuecomment-1620976672 , it wasnt updating because whole sidelist was not rendered as at all in zen mode. But now that side list is rendered and just hidden. So sise-list is re-rendered every time chapter changes and because chapter count is too high, it cause big lags. It is also the reason for scrolling not being smooth.

https://github.com/mienaiyami/yomikiru/issues/177#issuecomment-1634849687, though I did say that, I just made side-list render even in zenmode. I even tested it on epub with 500chapters but didnt see any issue at that time, but maybe I need to use this approach instead.

**Comment by mienaiyami** [comment]
> So you are saying you can make the reader smooth while scrolling, chapter transition, like it was before, right?

Yes, but it will result in the big lag when exiting zen mode. So, I think scrolling and chapter transition performance is preferred over this?

**Comment by mienaiyami** [comment]
As I said above. 
> I have been reading ORV with chapter count of 551 and there's no issue in it.

Even that is a lot for an epub.
I have fixed some performance issue related to #190, and lag will be less than before but won't be removing it just for a single epub file. 

https://github.com/mienaiyami/yomikiru/assets/84740082/3d6b7889-3d74-473f-adce-2a59ef487003

As you can see here, the lag in changing chapter is side list, and its better in zen mode.
Main reason for performance here is my lack of knowledge in epubs and the way im implementing features that need it.
Hope you understand.

**Comment by mienaiyami** [comment]
Very unlikely, as i said before, it will require me to make a new type of reader just like manga and epub, So, Im trying to clean old code that caused big problems when making epub reader.
