### ISSUE TITLE
Add option to disable fast search and use exact search in locations tab

### ISSUE THREAD

**Issue by Neurosploit** [mienaiyami/yomikiru#208]
### Description of the new feature / enhancement

In 2.6.0 a change was made to the search algorithm that added the following:
`Type name of item in results ending with \ to open it in reader. e.g. One Piece\.`
![image](https://github.com/mienaiyami/yomikiru/assets/11396035/0f0184dd-fd71-4e7e-a5ac-989de4d60015)

I would like to be able to search only on an exact match of the given searched string. In this case I would only expect the first result to be found. I'm not sure why the second result gets found. I'm not aware of a chapter being called that and the words are not in the name of the manga.
An alternative would be to add double quotes. For example "one piece" would only match on an exact match of the given string somewhere in the path to the file (or chapter names).

### Scenario when this would be used?

Always, The current search is so confusing for newcomers of the application. 
They don't expect the current behavior and these results to pop up. I would like to be able to disable this behavior or have an option to use an exact search to make searching easier.
The image linked is already a very specific search and the behavior only gets worse if the search string is even shorter. Many results come up for manga's that are not matching the searched string.

**Comment by mienaiyami** [comment]
> In 2.6.0 a change was made to the search algorithm that added the following:
> `Type name of item in results ending with \ to open it in reader. e.g. One Piece\.`

This type of search has been in app even before that version. Maybe even before it was public.
As you probably know and see that manga titles can be very long, and even for normal length, I found it annoying having to type whole. There was also the case of abbreviation like "Tensura" "Danmachi"  where they werent present as whole in title of 
manga.
So i just made it to search using letters instead. Like "op" will match for "O`ne` P`iece`" or "O`ne` P`unch` man".
Never thought it will cause problem, but I guess it is. 
> An alternative would be to add double quotes. 

This will be the better way to do it.

**Comment by Neurosploit** [comment]
Understood. Please go with the alternative for this feature request and add double quotes to search.

**Comment by mienaiyami** [comment]
added in v2.16.0
