### ISSUE TITLE
Temporary data error

### ISSUE THREAD

**Issue by GenoXu** [mienaiyami/yomikiru#212]
### Type of installation

Portable (.zip)

### Steps to reproduce

I open a cbz file (or whatever archive file) so it gets extracted into the temp directory. After few days, I get this error when I try opening the same file (due to some temp data auto-deletion I think). 
I fixed it by manually deleting the temp folder of that file.
I was wondering if you could automate this or something (Maybe an option to vacuum temp data when facing this problem, or an option to detect data deletion and re-extract the file based on that)..

https://github.com/mienaiyami/yomikiru/assets/31614025/9c3497f3-dc05-4d31-91ca-b32701c4b74a

**Comment by mienaiyami** [comment]
Is that folder auto cleaned by window or some other app? I added option to select custom temp folder because of this reason. 
Anyways, I will add one more check on it.

**Comment by mienaiyami** [comment]
By the way, is extracting speed similar to 7z or winrar? I cant help but wonder from the video above.
I tested multiple times and its a lot faster than file manager's, though its still not as fast as 7zip or winrar its still comparable to them.
If not, I will try to check global paths for 7zip and using it if possible.

**Comment by GenoXu** [comment]
Oh.. it's a misunderstanding on my behalf then, because The original path was `C:\Windows\Temp` (shifted to explain the issue).

**Comment by GenoXu** [comment]
> By the way, is extracting speed similar to 7z or winrar? I cant help but wonder from the video above. I tested multiple times and its a lot faster than file manager's, though its still not as fast as 7zip or winrar its still comparable to them. If not, I will try to check global paths for 7zip and using it if possible.

Yes, 7zip is faster but the speeds are still comparable (a difference of 5-6s for my old machine).

https://github.com/mienaiyami/yomikiru/assets/31614025/0ac05361-1bb2-48b6-9b68-e66d73d0f0df

**Comment by GenoXu** [comment]
@mienaiyami Now that I run on 64bit, I think the extraction speed got much more similar to 7zip



https://github.com/mienaiyami/yomikiru/assets/31614025/3c1726a4-9256-4f67-b92a-49360a8b9619

**Comment by mienaiyami** [comment]
I tried using 7zip, but unfortunately due to some reasons its slower than current unzipper when used in app.

**Comment by mienaiyami** [comment]
Adding more checks wasnt good for performance so I added option to clear all temp files. Still, I find it weird that images in temp folder are deleted but the source file isnt, Yomikiru is not the one deleting them.
