### ISSUE TITLE
Mark as unread

### ISSUE THREAD

**Issue by GenoXu** [mienaiyami/yomikiru#213]
### Description of the new feature / enhancement

Right-click option to mark a chapter as unread (when accessed by fault)
![image](https://github.com/mienaiyami/yomikiru/assets/31614025/5d8a25b8-137b-4583-85fe-3976a5023da3)

**Comment by mienaiyami** [comment]
Will take some time, I added context menu long time ago and they are really bad in scalability so I will be redoing them whole.

**Comment by GenoXu** [comment]
I recorded this bug in the default location: 

https://github.com/mienaiyami/yomikiru/assets/31614025/1da41f0e-27d9-4234-a70a-80fdafa5372a

**Comment by GenoXu** [comment]
@mienaiyami I recorded this bug in the default location: 

https://github.com/mienaiyami/yomikiru/assets/31614025/1da41f0e-27d9-4234-a70a-80fdafa5372a

**Comment by mienaiyami** [comment]
fixed, will be in next update.
