### ISSUE TITLE
Double Click Zen Mode

### ISSUE THREAD

**Issue by DeffyFM** [mienaiyami/yomikiru#214]
### Description of the new feature / enhancement

I intuitively thought it would be a feature to double click for zen mode, but it didn't work, and only realized later, that it only works on a narrow section of the image
So I would like to request to change to: Rapidly double click **any part** of the image to enter/exit zen mode

### Scenario when this would be used?

Anytime since it makes it more user intuitive to enter/exit zen mode,

**Comment by mienaiyami** [comment]
It works only in center 40% of screen, because rest part of screen is reserved for page mover in "left to right" and "right to left" reading mode.

**Comment by DeffyFM** [comment]
> I will increase area in "vertical scroll" mode.

Thanks!
![](https://images.emojiterra.com/google/noto-emoji/unicode-15/animated/1f44d.gif)
