### ISSUE TITLE
Double click zen mode in epub

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#219]
### Description of the new feature / enhancement

Double click left mouse button to enter / exit the zen mode in epub too just like you had implemented it for comics.

### Scenario when this would be used?

To enter / exit zen mode using mouse.

**Comment by mienaiyami** [comment]
I was adding this, but then thought about text select which I usually do (selecting after double clicked selects by words). So, I thought it might be a bad idea. If others fine, then I will add, I guess.
