### ISSUE TITLE
Page Number Freeze

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#22]
Page number freezes only when the side list is pinned. When it is unpinned the page number counter works.

**Comment by mienaiyami** [comment]
Can you please show it in work? I'm sure i have fixed that and I currently tested it and its working.
**Note: If you are reading manhwa, they usually have very long images, so page number doesn't change for many scrolls. I can't do anything about that as I count image as page.**

**Comment by mienaiyami** [comment]
> If you want to show video on manga reader repository home page rather than the link, hit enter after link.
Thank you very much.

**Comment by mienaiyami** [comment]
Fixed.
Will push update after 1day along with stutter issue fix if possible.
