### ISSUE TITLE
Yomikiru Doesn't Run on Windows 10

### ISSUE THREAD

**Issue by AstroHiker** [mienaiyami/yomikiru#223]
### Type of installation

Setup (.exe)

### Steps to reproduce

Hello, 

The Readme doesn't state operating system requirements, but even so I decided to give this program a shot. 
When I first installed Yomikiru, months ago, it was on v2.8.1. On first launch it was okay for the first minute, then closed on it's own. A window popped up stating "Yomikiru has stopped working": 

![Yomikiru has stopped working](https://github.com/mienaiyami/yomikiru/assets/141143335/afedbff3-7fa0-4d5d-bac3-b74e3e75972c)

I tried a handful of times, but this window came up without fail, before I could open any settings or manga. 

Later I tried again on v2.16.0. I was excited to see a Windows 64-bit setup.exe. After installing it, the same scenario as above stopped Yomikiru in it's tracks. This time, I opened up Windows Compatibility Troubleshooter and trued some things. 
The first was to try it in Windows 8 compatibility mode. 

![First Try to Fix](https://github.com/mienaiyami/yomikiru/assets/141143335/7bf90d44-7f2a-4998-b821-de353aea4086)

But it only lead to the same "Yomikiru has stopped working" window. Next was to try Windows 7 compatibility mode. 

![Yomikiru Solution](https://github.com/mienaiyami/yomikiru/assets/141143335/dbb0628a-38bf-4fd9-8ea6-637736e31994)

Finally, I was able to open a stable Yomikiru! I had plenty of time to browse through the settings, and leaf through a manga. So I closed the Troubleshooter and started using it. 

![Yomikiru Solution 2](https://github.com/mienaiyami/yomikiru/assets/141143335/bfc68454-dd1e-4b0f-be91-ba4dd0f4d056)

I've since updated to v2.16.2, but I still need compatibility mode to properly run your program. 

From here you may be asking, "Well, it works. So what's the problem?". 
I'm writing this to ask you to update your software to run on Windows 10, and 11. Right now, it only runs on Windows 7, and crashes on current versions. Since it won't run on 10, I'm assuming it hasn't been updated to 11 either. Windows 10 is slowly on it's way out and the majority of new computers sold today are running Windows 11. This incompatibility severely limits the accessibility of your program and common people don't have the time or know that they can troubleshoot compatibility. Please update your program to current windows operating systems. 

My Setup: 
Windows 10 Home 64 Bit 
HP Envy 17" Laptop
 Yomikiru v2.16.2, Windows 7 Compatibility Mode

**Comment by mienaiyami** [comment]
It is possible that your antivirus software might be deleting some of app's files, so please check that as well.
On addition to what I said above for logs. You can also send logs from "<your-app-path>\userdata\logs".

**Comment by AstroHiker** [comment]
Thank you for your quick response mienaiyami. Based on your suggestions, here's how it went: 

1. Check for Antivirus interference: 
Uninstalled Yomikiru. Turned Wifi Off. Restarted computer. Disabled Anti-Viruses. Do a fresh Yomikiru install. Try to open. Result? 
- Initial Stopped Working pop up appeared. 

2. Submit Log: 
Here's the log file. 

[main.log](https://github.com/mienaiyami/yomikiru/files/12230533/main.log)

And a breakdown of what I did for each timestamp: 

6:27-7:02 used the normal Windows 10 Compatibility with Wifi and Antivirus off. It seems the log didn't catch the crashes, since there are no "quitting" logs. 
7:09-7:17 is the return to Windows 7 Compatibility. 
7:22-7:27 takes it a step further with antivirus and wifi back on.

**Comment by mienaiyami** [comment]
> main.log

Files in "logs" folder are generated while using app so they dont log all the data for performance. 



> Can you try this for some more information about the error.
> 
> 1. Get the portable version of app.
> 2. Go to the folder where app is located.
> 3. Open terminal there, by either right click menu or entering "cmd" in top of file explorer where it shows current folder (e.g, "D:\downloads").
> 4. `.\yomikiru.exe --enable-logging=file --v=1` paste this and click enter.
> 5. After window closes, go to "userdata" folder in same folder where Yomikiru.exe was, and upload the `electron_debug.log` file here for more help.

Please do this instead.

---



> 6:27-7:02 used the normal Windows 10 Compatibility with Wifi and Antivirus off. It seems the log didn't catch the crashes, since there are no "quitting" logs.
> 7:09-7:17 is the return to Windows 7 Compatibility.
> 7:22-7:27 takes it a step further with antivirus and wifi back on.

What are these related to?

**Comment by AstroHiker** [comment]
> > main.log
> 
> Files in "logs" folder are generated while using app so they dont log all the data for performance.
> 
> > Can you try this for some more information about the error.
> > 
> > 1. Get the portable version of app.
> > 2. Go to the folder where app is located.
> > 3. Open terminal there, by either right click menu or entering "cmd" in top of file explorer where it shows current folder (e.g, "D:\downloads").
> > 4. `.\yomikiru.exe --enable-logging=file --v=1` paste this and click enter.
> > 5. After window closes, go to "userdata" folder in same folder where Yomikiru.exe was, and upload the `electron_debug.log` file here for more help.
> 
> Please do this instead.
> 

I'll get on it. 

> > 6:27-7:02 used the normal Windows 10 Compatibility with Wifi and Antivirus off. It seems the log didn't catch the crashes, since there are no "quitting" logs.
> > 7:09-7:17 is the return to Windows 7 Compatibility.
> > 7:22-7:27 takes it a step further with antivirus and wifi back on.
> 
> What are these related to?

If you open main.log, you'll see those timestamps. I added that description because the log file itself isn't detailed.

**Comment by mienaiyami** [comment]
Will be closing this issue as stale in a week.

**Comment by AstroHiker** [comment]
Hello everyone, 

Thank you for the resposnes. Sorry for my delay. Work had ramped up. 

1. "Did you try running latest version without any compatibility mode Yes, it takes a while to load the UI, but once it does it stops working within a few seconds. 

2. Get the portable version of the app and check log files. 
Same result without compatibility mode. Here's the portable's log file from user data. 

[electron_debug.log](https://github.com/mienaiyami/yomikiru/files/12365591/electron_debug.log)

**Comment by mienaiyami** [comment]
Im guessing its because of high ram usage. Does the app close without doing anything or after opening a manga? 
Can you try opening a folder with few images.

**Comment by AstroHiker** [comment]
It closes without doing anything. I opened it, started a stopwatch, and left it alone. Stopped working pop up appeared after 55 seconds.

Here's the new log file: 
[electron_debug.log](https://github.com/mienaiyami/yomikiru/files/12367430/electron_debug.log)

**Comment by AstroHiker** [comment]
I should also note that after your comment, I monitored my PC's RAM memory through task manager. It was sitting at 73% memory usage before opening the app, and 75% usage during. The extra 2% was only 102 MB from the app. 
I don't think high memory usage is the culprit.

**Comment by mienaiyami** [comment]
It's really hard for me to pin point the issue, most of the users are windows 10 and 11, and never had such issue.
You may want to check if your anti-virus is closing it. From my side I had made it so it runs on all major Windows versions. 
From the logs you provided, it does not look like it's Yomikiru's fault.

There is a system way to check it
1. Launch "Event viewer".
2. Navigate to "Windows logs" and then the "Application" tab.
3. Check for any errors in it. 
4. Also check other tabs alongside it as well,

**Comment by AstroHiker** [comment]
Yeah, it really is hard to diagnose something remotely. Thanks for your continued attention to this.

I didn't know about the Event Viewer. It does show some logs, but the material is outside of my knowledge. I've saved it and will share here. Looks like you can open it by importing to your event viewer. 

[Yomikiru Has Stopped Working Event Logs_1033.zip](https://github.com/mienaiyami/yomikiru/files/12369453/Yomikiru.Has.Stopped.Working.Event.Logs_1033.zip)

**Comment by mienaiyami** [comment]
It also requires `.evtx` file that is generated alongside it. 
But that might be useless for me if there is no "Error" written where "information" is 
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/8747874a-e4f8-4e26-b168-58d41657947d)

And even after that, if it's something windows related, I might not be able to help much. 
If you have pro version of windows, then you can even try running this app in windows sandbox.

You can try running these command in cmd as admin.
```
sfc /scannow
DISM.exe /Online /Cleanup-image /Restorehealth
```
Again just check for drivers and windows update.

**Comment by AstroHiker** [comment]
Oh my bad. Here's the updated zip file. Yes, you'll see Error there with a red icon. 
[Saved Windows Error Logs.zip](https://github.com/mienaiyami/yomikiru/files/12370503/Saved.Windows.Error.Logs.zip)

**Comment by mienaiyami** [comment]
Thanks for the logs.
It seems your system is some files in your system are corrupted or missing.
You can try this to get the latest files. Generally, it is recommended that everyone should run this setup on a new PC/laptop.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022:~:text=Permalink%20for%20latest%20supported%20x64%20version.%20The%20X64%20Redistributable%20package%20contains%20both%20ARM64%20and%20X64%20binaries.%20This%20package%20makes%20it%20easy%20to%20install%20required%20Visual%20C%2B%2B%20ARM64
Restart your PC just in case, after installing these.
It will most likely fix the issue.
If it doesnt, you can follow this guide. https://windll.com/dll/microsoft-corporation/msspellcheckingfacility
