### ISSUE TITLE
Lone record is focused in continue reading

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#225]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Open any file and close it.
2. Lone record is focused in continue reading when the 'Bookmark / History Search' option is enabled.

---

1. Also, when there are multiple records it does not happen.
2. But remove the records until only one record is present.
3. The lone record is focused again.

### ✔️ Expected Behavior

For the lone record to not be focused.

### ❌ Actual Behavior

Lone record is focused.

**Comment by mienaiyami** [comment]
I did fix this but forgot to check when bookmark/history search is enabled. Thanks for letting me know.
