### ISSUE TITLE
Text color secondary is not resetting

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#228]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Change text color secondary to any color.
2. Click on reset button, its not resetting and causes unexpected behavior. (Others are resetting).
3. In the below video, Unexpected behavior,
4. I chose red and its not resetting.
5. So I chose white, but when I had clicked on reset button it went back to red color instead of the original color.

---

### ✔️ Expected Behavior

For the text color secondary to reset.

### ❌ Actual Behavior

Text color secondary is not resetting.

**Comment by mienaiyami** [comment]
Unable to reproduce. Maybe the original color might be set to red or there might be some other steps to cause this. 
Try refreshing with the same theme selected.
