### ISSUE TITLE
Epub Font, Link color appear on screen after opening and closing dev tools

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#229]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Open any epub.
2. Change font color to any other color.
3. Open dev tools (Ctrl+Shift+i) and Close it.
4. Font color selector is on the screen.
5. For the link color selector to appear, repeat from step 2 using link color.
- The first time the dev tools are opened in the below video is to show that it does not appear before doing step 2.

https://github.com/mienaiyami/yomikiru/assets/127277950/a16918df-ca8e-4fcc-ac14-17b4c8dc2d1e

### ✔️ Expected Behavior

For the font, link color to not appear on screen.

### ❌ Actual Behavior

Font, link color appear on screen.

**Comment by mienaiyami** [comment]
same as #230.
