### ISSUE TITLE
Side effect of choosing themes anywhere (theme maker, reader settings)

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#230]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Change a theme of background / font / anything from theme maker in settings.
2. Even if the reset button is clicked or not, it does't change the outcome.
3. Open any manga/epub.
4. Open and close dev tools.
5. The last used theme selector appears on screen.
6. The changes made to the theme can also be seen.

---

1. Open any manga and change custom color filter to any other color.
2. Open and close dev tools.
3. The same is repeated.

---

### ✔️ Expected Behavior

For that side effect to not occur.

### ❌ Actual Behavior

Side effect occurs.

**Comment by mienaiyami** [comment]
I forgot to type the reason in 299, but in short I forgot to re-add a single line after testing it, and it was responsible to removing the color element, now its just hiding it.
