### ISSUE TITLE
Button hover color

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#235]
### Type of installation

Portable (.zip)

### Button hover color not working on hovering over active link variables

1. Open theme maker.
2. Change button hover color to another color.
3. Hover on active link variables in theme maker.
4. Hover color is not showing on active link variables.

### ✔️ Expected Behavior

To work on hovering over active link to variables button.

### ❌ Actual Behavior

Not working on hovering over active link to variables buttons.

**Comment by mienaiyami** [comment]
Reader setting labels are just some exceptions. It requires extra code to make it work like that, which I think is a waste of time.
