### ISSUE TITLE
Reading double pages

### ISSUE THREAD

**Issue by GenoXu** [mienaiyami/yomikiru#241]
Some manga pages are double width.
To be able to read such pages, there is an option  in CDisplayEx to zoom them into 150%, 200% or even 400% the original size using shortcuts (I use `ctrl`+`Backspace` to zoom 150% & `Ctrl`+`Enter` to go back to 100%)

![image](https://github.com/mienaiyami/yomikiru/assets/31614025/3481512d-bad4-45e8-b04a-de352d750b08)

**Comment by mienaiyami** [comment]
Can't you do that already in Yomikiru? Or do you mean a keyboard shortcut for it?
You can use ctrl+scroll (resize) and shift+scroll (scroll horizontally)

**Comment by mienaiyami** [comment]
Now that I checked it again, there seems to be an issue with it. Some of the images are cut and do not scale beyond their original size. 
I'll check.

**Comment by GenoXu** [comment]
> Can't you do that already in Yomikiru? Or do you mean a keyboard shortcut for it? You can use ctrl+scroll (resize) and shift+scroll (scroll horizontally)

Yes, I am asking for shortcuts; one for zooming by 50% (for example) and one for zooming back into the original size.

> Now that I checked it again, there seems to be an issue with it. Some of the images are cut and do not scale beyond their original size. I'll check.

And yes, I also remarked this misbehavior (so I suggested the shortcut thing).

**Comment by GenoXu** [comment]
+ I noticed that I can't resize the page unless I change the reading mode into Free (even though I prefer reading while fitting the width)..

**Comment by mienaiyami** [comment]
I only added current options temporarily, you can check in settings -> shortcutkeys.
The current shortcut system of app don't properly support keys like ctrl, shift or alt. I will make these shortcut customizable when i improve current system.

**Comment by GenoXu** [comment]
Fine, but it's jumping to the top every time I resize the page

https://github.com/mienaiyami/yomikiru/assets/31614025/e412a73c-d3f9-4f94-90ea-e3b7b9d3cbc1

**Comment by mienaiyami** [comment]
Wasn't in my tests. I'll check.

**Comment by mienaiyami** [comment]
I wasnt able to replicate this, but I tried something that might fix this, please report if it still does that.

**Comment by GenoXu** [comment]
Now that the jumping bug is fixed, I report two other things :)

1. The zooming scale is too big compared to CDisplayX (150% in Yomikiru == 200% in CDisplayX)

![image](https://github.com/mienaiyami/yomikiru/assets/31614025/ef3cc5ac-079e-4f84-ba11-1af3b7fb62ee)
![image](https://github.com/mienaiyami/yomikiru/assets/31614025/2ba01b5a-1447-485d-a939-ce48057ef145)
![image](https://github.com/mienaiyami/yomikiru/assets/31614025/e1c3897b-353f-49ac-a402-1b6ac3d98710)


2. Double pages are still cut when scaled

https://github.com/mienaiyami/yomikiru/assets/31614025/7a41d1ff-299f-45b5-8be0-70a33fe05abf

- ([Here](https://drive.google.com/uc?id=18TiL3zRsrma6W-WzWRNkOMi478Hm9TJ7&export=download)'s the cbz file used for replication testing)

**Comment by mienaiyami** [comment]
> 2\. Double pages are still cut when scaled

I found the cause, will be fixing in next update.

Also, I doubt that 1. got fix, I couldnt test it. But fixing 2. will fix that automatically.

**Comment by GenoXu** [comment]
1. is fixed indeed (for single pages only), but 2. persists (actually got worst)

https://github.com/mienaiyami/yomikiru/assets/31614025/772d9d36-c4d8-4d1b-91ec-c081f7cb00d3

**Comment by mienaiyami** [comment]
I couldnt test everything, so please report if you see any issue.

**Comment by GenoXu** [comment]
Unfortunately, nothing changed
You can test out the results on this chapter file (page 6 is the one shown above):
https://drive.google.com/uc?id=1iR8Q9ENPBIR-gIdjtEak3d8B7ToNTrLJ&export=download

**Comment by mienaiyami** [comment]
Some changed caused it to break for "Page per row - 1". Also it will only work with this enabled.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/a87b852b-426e-4038-b5f8-9237294c4028)
