### ISSUE TITLE
Progress Indicator in .xhtml / .txt file

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#249]
### Type of installation

Portable (.zip)

### Steps to reproduce

1.Open any .txt / .xhtml file.
2. Shows page indicator instead of progress % when a single .xhtml / .txt file is opened.

### ✔️ Expected Behavior

To show progress %.

### ❌ Actual Behavior

Shows page indicator.

**Comment by mienaiyami** [comment]
It's still experimental. But I think that might not be possible. It will still show progress in zen-mode though.
It is not the only issue, and most likely other might not be fixable either, because of how it works,

**Comment by mienaiyami** [comment]
As I said before in #202, its not really ideal to make a new type of reader, txt and xhtml files are opened in epub-reader but as a manga-item instead, because its structure is same as manga and not a epub, like having a main folder as "manga" and files as "chapter" and many other things.

**Comment by mienaiyami** [comment]
> In my opinion, it would be better to make the .xhtml files (As these are the chapter files). And do not bother about the stylesheet links, images in individual .xhtml files.

Im not linking anything, it's just single file. 

The problem here is that, the progress/page-number is not part of reader, I use some global state to decide whether it will show progress or page-number, and that is just the data itself, which currently is either a Manga-Item or EPUB-Item.  
Side-list and settings were easy to add as they are inside readers.

**Comment by mienaiyami** [comment]
> * Wouldn't it be better to create a new reader.tsx file only for the individual .xhtml files.

It's not a bad solution, until you think about how many issues there are in each reader itself, then imagine if there is some book related problem, i will need to fix it for all the files, and on top of that, almost 90% of it will be same. And if you look at each reader.tsx file, they are very big. It will be hard to manage all that. 
I'm already finding it hard to manage Yomikiru related things now. On my personal todo list there are over 10 bugs and around a few more things which work but not like it should, for example I recently added ability to click alphabet to focus element on a select menu, there are lot of such issues left.
