### ISSUE TITLE
Read xhtml / txt files

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#251]
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Open any xhtml / txt file.
2. Go to home.
3. The read xhtml / txt file is highlighted even when the record chapter read option is disabled in app settings.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/f96cb066-87d4-43db-8123-5ec1659a77b4

### ✔️ Expected Behavior

To not record the read chapter when the option is disable in app settings.

### ❌ Actual Behavior

Read chapter is recorded even when the option is disabled.

**Comment by mienaiyami** [comment]
Yes, I have fixed both of them. Not released yet.

**Comment by mienaiyami** [comment]
> Also, the history is not working.

You mean scroll history? Unfortunately, that wont work.
Im planning to make its own reader later when I fix all my higher priority issues.
