### ISSUE TITLE
Dbl-Click Zen Mode

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#253]
### Description of the new feature / enhancement

Why not type the word in its complete form?
- Dbl-Click Zen Mode - > Double Click Zen Mode

**Comment by mienaiyami** [comment]
I was concerned about the size of the context menu itself. All other items have low text length.

**Comment by mienaiyami** [comment]
It also had "enable text select" but i removed it later , and forgot to rename it

**Comment by mienaiyami** [comment]
Will be in next update.
