### ISSUE TITLE
Display images as they're read from cbz/cbr for Vertical Scroll

### ISSUE THREAD

**Issue by emanuelsipos** [mienaiyami/yomikiru#270]
### Description of the new feature / enhancement

You would be able to scroll through images as they're read from disk, without waiting for all of them to load.

This would make for a more pleasant experience, as the first images are displayed faster, and the rest can load while you're on the first couple of images.

An example of this would be YACReader for iOS, which opens chapters without delay, and loads the rest while you're reading, clearing them from memory after it's a distance off-screen.

### Scenario when this would be used?

While using Vertical Scroll.

### Supporting information

YACReader webtoon example:

https://files.catbox.moe/t5clg9.MP4

**Comment by mienaiyami** [comment]
Its already done experimentally. 

> clearing them from memory after it's a distance off-screen.

Its not really possible because of the app's framework,

**Comment by emanuelsipos** [comment]
Can't wait for it to be released then :)

> Its not really possible because of the app's framework,

Phones can probably use the extra RAM saved, I don't think it's that important for PC. Faster loading time is all I'm hoping for.

**Comment by mienaiyami** [comment]
> I want to ask this before its too late, will the dynamic image loading / lazy loading of images be as an option?

It is the main feature i added. 

Though I still haven't checked everything yet, it's not possible to just read a single image from archives using the tools I use.

**Comment by mienaiyami** [comment]
> Will this dynamic loading only apply to archives?

Archives cant be loaded dynamically. They must be extracted first, as of now, 

It can be enabled from settings and is not enforced.

**Comment by mienaiyami** [comment]
As I said above, I can't load single files from archives using the current tools, so this request is not possible unfortunately.
However, I have added dynamic loading for folder type, to show chapter instantly.
