### ISSUE TITLE
Automatic anilist progress

### ISSUE THREAD

**Issue by mienaiyami** [mienaiyami/yomikiru#279]
### Description of the new feature / enhancement

Update anilist progress automatically as you read.

**Comment by gaurav4152** [comment]
Hi there, I am having an issue while login with anilist of "invalid token/error".Can you help me with that?

**Comment by mienaiyami** [comment]
@gaurav4152 
It may be due to very recent changes in Anilist. If you notice, it now asks for human verification each time. 
I will wait and see if it fixes automatically after some time.

**Comment by mienaiyami** [comment]
@gaurav4152 <https://anilist.co/forum/thread/68889>. Its Definity some issue from Anilist's side so just wait it out.

**Comment by gaurav4152** [comment]
Woah ,you are right its the issue with anilist !
Thanks for the reply! :)

**Comment by mienaiyami** [comment]
Yes, thanks for the suggestion.
