### ISSUE TITLE
scroll down bug

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/yomikiru#293]
When I want to open a folder, it goes scroll down it doesn't come first and  if can add dynamics loader to pdf too can good

**Comment by mienaiyami** [comment]
Can you give more details? or a screen recording, that will be helpful.

**Comment by wolfkingal2000** [comment]
> Can you give more details? or a screen recording, that will be helpful.

this video show up bug 

https://github.com/mienaiyami/yomikiru/assets/131250049/a5ded244-a327-4a7e-ab75-75fd473f16f6

**Comment by mienaiyami** [comment]
This is expected (even stated in the dynamic loading option), because size of images is not known unless they are loaded it create such scroll issues.
