### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#295]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

None

### Steps to reproduce

1. Go to reader side list.
2. Change icon color.
3. The icon colors of reader side list are unchanged.

### ✔️ Expected Behavior

For icons to change colors when the icon color is changed in theme maker.

### ❌ Actual Behavior

Reader side list icons not changing colors.

**Comment by mienaiyami** [comment]
Sorry for no fixes in past month, I was busy with college work.
