### ISSUE TITLE
Allow the current scroll speed feature to effect mouse scrolling as well

### ISSUE THREAD

**Issue by Advonso** [mienaiyami/yomikiru#297]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

Allow the current scroll speed feature to effect mouse scrolling

### Scenario when this would be used?

Using mouse scroll

**Comment by mienaiyami** [comment]
Was this closed by mistake or because it wasnt needed? I always believed middle mouse button was enough so I never added scroll speed modifier.
