### ISSUE TITLE
Better Theme System

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#299]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

- The current theme system is advanced, yet complicated and has some bugs, because of how complicated it is.
- Its really has too many properties (34) which is exhausting, tbh.
- So I would like to suggest a simple, better and essential theme system. (In my opinion).
- My suggested / requested theme system would have 8 properties instead of 34 properties of the current theme system.
- This would be a simple and essential, yet ample theme system.

### Simple Theme System with 8 essential, accurate properties.
| No. | Property | Description |
| --------- | ----------- | ----------- |
| **1.** | **Text Color Primary** | Changes all primary font colors. (Including The Top Bar Yomikiru Name Color - This is currently linked to icon color). |
| **2.** | **Text Color Secondary** | Changes all secondary font colors. (Like the chapter name in the continue reading tab). |
| **3.** | **Icon Color** | Changes all the icon colors. |
| **4.** | **Button Color** | Changes all the button colors. |
| **5.** | **Hover Color** | Changes color when hovered on list, buttons, items, reader side list chapter hover, etc. |
| **6.** | **Code Background Color** | Changes the color of code background. (Code text linked to text color primary.)|
| **7.** | **Chapter Read Color** | Changes the colors of chapter read in every place like reader side list, location tab. |
| **8.** | **Interface / Body Color** | Changes the entire interface color (be it reader side list, background, top bar, etc.) except the above 7 property related ones. |
| | | **Note -** Reader background can be changed in color filters, so not a problem. For epubs the text, background color can also be changed in the reader settings. So keep them both as it is.|
| | | **Note -** Keep the existing transparent colors transparent with no change. **Example -** Zenmode page indicator background color. |

### Scenario when this would be used?

- For a simple, essential, bug free, and ample theme system.
- With this theme system even when a user needs to change or save a new theme he/she likes, then it would be very easy as this has 8 essential properties which are ample.

### Supporting information

- If you choose to implement this, then please keep the color filters tab in reader settings as it is, as the reader background color can be changed without affecting the entire theme of the program.
- Also keep the font, background, progress backround, and link color of epub reader settings as it is, as they are very useful to change color directly without changing the theme / interface related color settings.

**Comment by mienaiyami** [comment]
It does sound like a nice idea but I can already imagine people asking for more customization options. 
But that aside, there's another issue that's causing so many theme variables, that is the whole UI. I'm not good at UI design and it resulted in using many colors.
I do plan to do something similar however, but it will only be possible if I plan to change UI design.

Though, personally I don't think its that much needed as you can already see in default theme, they are linked to few main colors.
Link feature was literally implemented for this reason.
