### ISSUE TITLE
some jpg images are not opening

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#30]
Not all jpg format images, but some are not opening up in manga reader.

- I uploaded the folder which is not opening for me in the application.
- This is the first time I encountered this issue in the application.
- To make sure, I checked again with another manga that is in jpg and it works fine.

### This is what happens,

![screenshot](https://user-images.githubusercontent.com/111482404/204086080-f3179542-eb9d-46bf-b489-4c8e4f417bce.jpg)

### Please check the below folder that has the images.
[#1 - Episode 1.zip](https://github.com/mienaiyami/react-ts-offline-manga-reader/files/10096119/1.-.Episode.1.zip)

**Comment by mienaiyami** [comment]
The image element excepts a "link/url" and "#" is used to show fragment, for example, https://github.com/mienaiyami/react-ts-offline-manga-reader#features, notice **#features** at the end.
