### ISSUE TITLE
"Navigate to page" not working properly (testing with cbz file)

### ISSUE THREAD

**Issue by gsxgmpkt9020** [mienaiyami/yomikiru#301]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

image

### Steps to reproduce

Navigate to page with mouse or f shortcut

![comic](https://github.com/mienaiyami/yomikiru/assets/2074641/7c6d4bb0-88b4-4eb5-bb58-9312c64dac69)

### ✔️ Expected Behavior

Navigate to page 

### ❌ Actual Behavior

Cannot Navigate to correct page.

If I want to jump to 188, it will only jump to 39; if 288, only 90

**Comment by mienaiyami** [comment]
I just checked this on a cbz with 250 pages and it was working without any issue.
Could you share some more details?

Note that when you click and move cursor while it is scrolling to the page, it will cancel the scroll and you will be on the page where you started dragging mouse.
