### ISSUE TITLE
Add "scroll speed setting" tooltips

### ISSUE THREAD

**Issue by pein0saga** [mienaiyami/yomikiru#302]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

"Scroll A, Scroll B" is not informative.

Please add  tooltips to be informative.

```
Scroll A = Scroll up / down using w/s (Customizable in shortcut keys)
Scroll B = SpaceBar (Customizable in shortcut keys)
```

_Originally posted by @omodia in https://github.com/mienaiyami/yomikiru/issues/296#issuecomment-1752274079_

### Scenario when this would be used?

Setting up scroll speed

**Comment by mienaiyami** [comment]
I have tried it before, but it does not fit well in the UI. But I Scroll speed main label does have a tooltip.
