### ISSUE TITLE
Can't open rar files

### ISSUE THREAD

**Issue by PagChompman** [mienaiyami/yomikiru#307]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

image

### Steps to reproduce

This pops up when I try to open rar files, zip files work fine. 
I have tried reinstalling both the program and winrar to the lastest version. Both are at default settings. 
![Yomikiru-7754](https://github.com/mienaiyami/yomikiru/assets/74179384/32038fc9-2533-47d2-bfaf-aee4c925f5bc)

**Comment by mienaiyami** [comment]
You need to have winrar installed for it to work. It also need to be in PATH, [follow this](https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)) and add winrar folder,
