### ISSUE TITLE
Duplicate option in settings

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#309]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

None

### Steps to reproduce

1. There is a duplicate option in settings.

![1](https://github.com/mienaiyami/yomikiru/assets/127277950/cec88fcc-33b4-4baf-9e82-d4e1fc364899)

### ✔️ Expected Behavior

No duplicate options

### ❌ Actual Behavior

A duplicate option

**Comment by mienaiyami** [comment]
One is for manga only and other is for epub only.
