### ISSUE TITLE
Auto-Focus current chapter icon

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#311]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

- The show/hide list button doesn't have any option in the settings, but works as it is intended.
- In the same way for the auto focus icon without any option to toggle it on / off in settings.
- The wording needs to be 'Auto-Focus Current Chapter' instead of 'focus current chapter' in the pop-up on hover.

---

![1 - Copy (2)](https://github.com/mienaiyami/yomikiru/assets/127277950/8ee14acc-8d97-42b5-863c-a56aa3352ecd)

### Scenario when this would be used?

To not be confused.

### Supporting information

The two options in settings are redundant and not needed.

---
![Untitled](https://github.com/mienaiyami/yomikiru/assets/127277950/036b3954-1fc3-42e2-8f2c-592b1f99a1d1)

**Comment by mienaiyami** [comment]
Both are different options, the one in settings disables existing "auto focus current chapter on chapter change", while the button in  side-list focuses current chapter on demand only (i added this as a fallback when you have option in settings disabled, but also works when on high chapter count when you scroll too much), its not related to "auto focus".
