### ISSUE TITLE
How to sort chapter in correct order (i.e. chapter 1 must come before chapter 1.1) 

### ISSUE THREAD

**Issue by shortbach** [mienaiyami/yomikiru#314]
### Question

I notice that some series have extra chapters that are named with chapter x.1 or chapter x.5.

The problem is that these kind of chapter are always sorted before their respective main chapters (i.e. chapter 1.5 folder is placed before chapter 1 which is not supposed to happen that way) which make reading annoying since you are reading the chapter in incorrect order. Is there a way to force window or at least Yomikiru app to recognize that Chapter 1.1 is supposed to come after Chapter 1 and so on?

**Comment by shortbach** [comment]
Thank you so much for the response but unfortunately it didnt solve the problem

![Screenshot 2023-12-16 173852](https://github.com/mienaiyami/yomikiru/assets/75778648/7a7aad8e-22cd-47e9-a96e-9f8325b9876e)

As you can see the chapters in red circle are in wrong order: chapter 315.1/2/3 are supposed to go after chapter 315. Some other app like Tachidesk somehow manage to show the correct chapter order (i.e. chapter 315 > chapter 315.1 > chapter 315.2 etc.) but I much much prefer this app.

**Comment by mienaiyami** [comment]
Thank for pointing it out @omodia.
I will see if its still possible.

**Comment by shortbach** [comment]
@omodia thank you for pointing that out. But all manga in my collection are in CBZ format so I cant afford to just extract them all, and I prefer to keep them in CBZ format as well

@mienaiyami I hope you release a fix to address the issue with CBZ format. FYI, sorting the file by Date Modified actually gives the correct order But sorting this way is not desirable.

![image](https://github.com/mienaiyami/yomikiru/assets/75778648/c91914a7-2b35-48a1-9287-f4369734cd9d)

Also for some reason, Tachidesk is able to display correct order even by sorting by name so there is a solution to this.

**Comment by mienaiyami** [comment]
> Also for some reason, Tachidesk is able to display correct order even by sorting by name so there is a solution to this.

Tachidesk uses the order from original source, you could have chapter 20 before 10 in its list.
While Yomikiru depends on filename.

**Comment by shortbach** [comment]
> > Also for some reason, Tachidesk is able to display correct order even by sorting by name so there is a solution to this.
> 
> Tachidesk uses the order from original source, you could have chapter 20 before 10 in its list. While Yomikiru depends on filename.

I see. In any case I hope you can work your magic to sort out the issue with the order of sorting by file name. I have tried all the popular manga reader app and Yomikiru is really the best one.
