### ISSUE TITLE
Remember reader setting for each individual series (Manga vs Webtoon)

### ISSUE THREAD

**Issue by shortbach** [mienaiyami/yomikiru#316]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

Webtoon and manga require different reader setting to display correctly. Example:

For manga, if you choose vertical scroll, you should leave "Double Size for double spread page" and "Gap between row" ON

However, for webtoon, those 2 settings should be turned off to be able to read correctly as intended.

And having to manually switch them on and off whenever you switch between manga and webtoon can be a bit inconvenient.

### Scenario when this would be used?

Manga and Webtoon series require different reader setting to display the pages correctly. Having the reader setting saved for each series in the library can be a nice quality of life feature.

**Comment by mienaiyami** [comment]
duplicate #281
