### ISSUE TITLE
How to force the app to show a double page image with 2 separate pages

### ISSUE THREAD

**Issue by shortbach** [mienaiyami/yomikiru#317]
### Question

A lot of manga series has double page but the problem is that the downloaded file contain 2 separate images (i.e. page 5 and page 6 are 2 separate image files but when shown side by side they create one big scene).

Is there any way I can do to make the app recognize that it is supposed to show 2 images together? by naming them in a certain way perhaps?

**Comment by mienaiyami** [comment]
There isnt any way to do this currently (individually), you can only choose between 1 page per row or 2 page per row and it will be applied to whole manga (i.e. pages will show up in pair, 1-2, 3-4, 5-6) but if a page with double width is detected it will be shown alone.

**Comment by shortbach** [comment]
> There isnt any way to do this currently (individually), you can only choose between 1 page per row or 2 page per row and it will be applied to whole manga (i.e. pages will show up in pair, 1-2, 3-4, 5-6) but if a page with double width is detected it will be shown alone.

I see it's unfortunate. Guess I have to find a way to join to pages into 1

**Comment by mienaiyami** [comment]
But I cant imagine the use case. If you are comfortable with 2 pages per row, shouldn't you be using it for whole manga?

If you really want to just view few pages like that, you can use the shortcut keys to switch between 1-page/row and 2-pages/row. By default its set to 1,2,3 on keyboard and can be changed in settings. Its quick and keeps the same page on screen.

**Comment by mienaiyami** [comment]
> So I was thinking if I could some how rename the page to something like ( 015,016-1 and 015,016-2 ) and the app will know to display 2 page together while reading in vertical scroll mode.

Wont renaming be equally time consuming as merging pages? You will have to go to pages and rename and open in Yomikiru again.

If you are having to merge/rename then anyways, why not just "temporarily" switch to "2 page per row" mode for that single page? 
**You can switch between 1page and 2page simply by clicking 1 and 2 on keyboard.** This feature is not related to reading mode (i.e. vertical, LRT, RTL). 
This is what I use when I am in same condition as you described. It is faster than renaming or doing multiple clicks to merge page in-app (is there was such feature). 

Maybe I didn't get what you mean?


Don't hesitate to comment even if the issue if closed, it can be reopened anytime if given proper reason.

**Comment by shortbach** [comment]
> > So I was thinking if I could some how rename the page to something like ( 015,016-1 and 015,016-2 ) and the app will know to display 2 page together while reading in vertical scroll mode.
> 
> Wont renaming be equally time consuming as merging pages? You will have to go to pages and rename and open in Yomikiru again.
> 
> If you are having to merge/rename then anyways, why not just "temporarily" switch to "2 page per row" mode for that single page? **You can switch between 1page and 2page simply by clicking 1 and 2 on keyboard.** This feature is not related to reading mode (i.e. vertical, LRT, RTL). This is what I use when I am in same condition as you described. It is faster than renaming or doing multiple clicks to merge page in-app (is there was such feature).
> 
> Maybe I didn't get what you mean?
> 
> Don't hesitate to comment even if the issue if closed, it can be reopened anytime if given proper reason.

Renaming is quick and takes no time at all. Usually manga downloaded is in .CBZ format, I can open it with 7zip, rename the image file and that's done, take no effort at all. But if I have to merge the 2 images together, I have to unzip the CBZ file, then find a tool to merge the file, make sure the output setting is correct, then execute the command, then download the file, then put it into the correct folder, then rename the file, then zip everything back, change the .zip extension back to .cbz. Imagine doing that for series with 30~70 volumes.

As for the solution to "temporary" switch reading mode with 1,2,3 keys, it's just a band aid solution. Usually I (and I imagine most users do too) read manga in full screen (zen mode) no cursor, I'm eating chips with my left hand, while my right hand scroll the mouse wheel, while leaning back on the chair. It's a hassle to have to sit back up, reach for the another key to change the reading mode back and forth.

The best thing about your app is that it offer the best User Experience. everything is quick and seamless and convenient, it does what users want the most and that is reading manga in the most comfortable way. The lack of beautiful UI is more than made up by its usability.

This is just my grip. I'm satisfied with the app as it is (believe me I have tried a lot of other apps on PC and your app is best) but I gives me suggestion for consideration hoping the app will continue to get better.
