### ISSUE TITLE
Vertical Scroll For EPUB files

### ISSUE THREAD

**Issue by KaanAlper** [mienaiyami/yomikiru#320]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

Menu in images
![image](https://github.com/mienaiyami/yomikiru/assets/86665266/18d7ecee-e615-4397-a9f5-900af62393e2)

Menu in EPUB's
![image](https://github.com/mienaiyami/yomikiru/assets/86665266/9d26efd7-54a9-448f-b5c8-e2eed6cc8cfd)

**Comment by KaanAlper** [comment]
> Vertical Scroll is already used for EPUBs.

But i need to use A and D key arrows for passing another page in Epubs

**Comment by mienaiyami** [comment]
> another page in Epubs

That is for chapters.

There is vertical scroll mode and can be enabled in settings, but I have not optimized it yet, so it will take high resources depending on the epub.

Disable this to for pure vertical scroll `Settings -> Other settings -> EPUB: Load by chapters`
