### ISSUE TITLE
merging as tom

### ISSUE THREAD

**Issue by Szeniel** [mienaiyami/yomikiru#325]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

Merging chapters as toms.
In setting: "Merg chapters into toms".
It would recognize name of chapters and it there is "vol 1" and so on, it would merge into one when reading, so in other words it would just make reading easier.
Because there would be less clicking.
Not like merging into 1 file, but more like reading without need of clickin to next file(chapter) only before new tom.
![image](https://github.com/mienaiyami/yomikiru/assets/113245289/9dd2d8a9-e4cf-460a-9d0c-6b7a4b7ee9bc)
![image](https://github.com/mienaiyami/yomikiru/assets/113245289/a2c5c4f8-9ccd-4748-82fc-a65d8b4af208)

**Comment by mienaiyami** [comment]
Like what @omodia said, its not very practical. And if you try to make them join using predefined name then again you will have to rename everything.
There are many tools available for this task, and in my opinion using them will be better.

I have plans for continuous reader that automatically add next/previous chapters without loading. That will kind of resolve your problem.

**Comment by Szeniel** [comment]
> Like what @omodia said, its not very practical. And if you try to make them join using predefined name then again you will have to rename everything. There are many tools available for this task, and in my opinion using them will be better.
> 
> I have plans for continuous reader that automatically add next/previous chapters without loading. That will kind of resolve your problem.

Thx this is what I was hoping for.
