### ISSUE TITLE
Focus current chapter --> Locate Current Chapter OR Locate Current Chapter In Side-List

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#329]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

Both image and epub reader related.

Currently the focus chapter icon does not reflect whether it is on or off.
It should reflect its status.

---

![b1](https://github.com/mienaiyami/yomikiru/assets/127277950/5831e83b-ca49-4738-8155-d171c3aa5397)

### Scenario when this would be used?

To know at a glance if its enabled or disabled.

### Supporting information

Example,
- When the list is enabled, the button changes to hide list. If the list is disabled it changes to show list.
- When the side list is pinned, the icon tilts indicating the list is pinned.

**Comment by mienaiyami** [comment]
Maybe you misunderstood it.

The button in side-list is not a toggle, when clicked, it only scrolls current chapter to view (in side-list). It only has one function, and is not a "state".

You might be confusing it with the "EPUB: Focus current chapter in side-list" which is different thing. It will toggle "auto focus current chapter when you change chapters. Finding and scrolling to the current chapter can be heavy if there are over 500 entries in side-list.

The button in reader can be used with "auto focus" disabled to prevent huge lag when moving through chapters, and still have the ability to show current chapter in a huge list.
