### ISSUE TITLE
Page break lines are visible in v2.19.0

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#333]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

image

### Steps to reproduce

1. Open any webtoon. I checked with multiple webtoons and this happens.
2. Select vertical scroll and disable page gap.
3. You can still see page gap even when disabled in v2.19.0.
4. When 1:1 is selected the page gap is visible, but lesser than when free size is selected.
5. This was not present in v2.18.5 be it small gap or large gap.

### ✔️ Expected Behavior

For the page gap to be not present regardless of free size or 1:1 like in v2.18.5.

### ❌ Actual Behavior

The page gap is present in both 1:1 and free size.

**Comment by mienaiyami** [comment]
It's very random issue and can't be fixed. Not only it's not reproducible its totally dependent on state of your machine.
It will probably go away if you restart your system. Similar to #169.

**Comment by mienaiyami** [comment]
> Is there no solution?

Im not sure what causes it. 
You can also try changing resolution/scale of you screen temporarily.
