### ISSUE TITLE
Backspace is not deleting keys

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#334]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

None

### Steps to reproduce

1. Open shorcut keys.
2. Select any key and press 'backspace' key.
3. The key is not deleted.

### ✔️ Expected Behavior

The key should be deleted when 'backspace' is used.

Its great to have 'x' beside each key to delete the key especially when only using the mouse to operate, but it would also be great to retain the deletion of keys using 'backspace'.

### ❌ Actual Behavior

The key is not deleted when 'backspace' is used.

**Comment by mienaiyami** [comment]
I was planning to make backspace to be usable in key bindings but forgot to remove it from reserved keys.
You can click `tab` and then `space/enter` to remove with keyboard.
