### ISSUE TITLE
Add New in shortcut keys tab and one other misc

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#335]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

None

### Open Yomikiru settings and go to shortcut keys tab.

**1. 'Add New' is not a button type and is not linked to button values in theme maker.**
- The change in mouse when hovered over a button is not replicated on 'Add New' button.
- And the text color of it is darker than other button colors.
- Example - 'x' button in shortcut keys is linked to all button values in theme maker and change in mouse can be seen on it.

https://github.com/mienaiyami/yomikiru/assets/127277950/0879013b-ad83-4384-8f31-f8a04c18794f

---

**2. Assigned shortcut key highlight.** 
- Disable the highlighting of assigned keys.
- It doesn't do anything, so highlighting is unnecessary.

https://github.com/mienaiyami/yomikiru/assets/127277950/8f3a4ae4-e4c0-4dac-9952-ab35986b32eb

### ✔️ Expected Behavior

1. 'Add New' should be a button type and should be linked to the button values in theme maker.
2. Assigned shortcut keys should not be highlighted.

### ❌ Actual Behavior

1. 'Add New' is not a button type and is not linked to the button values in theme maker.
2. Assigned shortcut keys can be highlighted.

**Comment by mienaiyami** [comment]
This is because they are "text inputs" and not buttons, previous version was also "text inputs". Using buttons here is not a great idea because buttons are meant to do some action on click, and there is none here. Here "Add new" is capturing many key clicks so its not a button.

As for the highlight, its not possible to remove it without disabling the whole element's mouse capture.

**Comment by mienaiyami** [comment]
It is the input placeholder color, which you might also see in search inputs.
I will see if there is a better way.

**Comment by mienaiyami** [comment]
Tried using button for "add new" and replacing it with input on click, but results in many unwanted behaviors. So for now I will keep it same.
