### ISSUE TITLE
after close app, dont close completely 

### ISSUE THREAD

**Issue by wolfkingal2000** [mienaiyami/yomikiru#338]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

image

### Steps to reproduce

Hello, when I close the program, it doesn't close completely and it is still working in Windows task manager. Thank you for fixing this.

**Comment by mienaiyami** [comment]
Can you give more details, like when it happens or how do you open the application. I checked on multiple OS and cant reproduce this behavior.

**Comment by wolfkingal2000** [comment]
I tried several times, the bug did not show itself, I will close these issues, if it shows again, I will open it again, then I will also record a video.

> Can you give more details, like when it happens or how do you open the application. I checked on multiple OS and cant reproduce this behavior.
