### ISSUE TITLE
Better Bookmarks Record

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#344]
### Type of reader (if reader related)

None

### Description of the new feature / enhancement

Same as #69, but the difference here would be one to many numbers of bookmarked chapters of that concerned manga/comic/epub/txt/webtoon would be under that name in a line.

The bookmarked time is only used for a better understanding of the feature request.

---

![Bookmarks](https://github.com/mienaiyami/yomikiru/assets/116664905/1f4397ea-76fa-4e45-a940-c96fe1354efe)

### Scenario when this would be used?

For better bookmarks record.

**Comment by mienaiyami** [comment]
This will make layout a bit weird. Clickable area for each title will be halved, and on top of there, there will be hanging manga name which no cursor action to fit in.
If I make each element same height then again it will look weird with empty space or larger text.
