### ISSUE TITLE
Open With Yomikiru On Context Menu

### ISSUE THREAD

**Issue by KaanAlper** [mienaiyami/yomikiru#346]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

When we rightclick folder there should be button like "Open with Yomikiru" or etc. Or after select multiple images

### Scenario when this would be used?

for folders
![image](https://github.com/mienaiyami/yomikiru/assets/86665266/83ccf8ce-7bc5-42ec-ad7f-60911bc5fc26)
or maybe after select multiple images
![image](https://github.com/mienaiyami/yomikiru/assets/86665266/84fb8abe-edad-4c05-a519-75c93e50f4ee)

**Comment by mienaiyami** [comment]
If the issue if not resolved, then please ask to re-open it.
