### ISSUE TITLE
"Error occurred while loading image" when trying to open Full Colored pages

### ISSUE THREAD

**Issue by himouto** [mienaiyami/yomikiru#351]
### Type of installation

Setup (.exe)

### Type of reader (if reader related)

None

### Steps to reproduce

Reader works fine on normal grayscale mangas but getting an error whenever I try to open a manga with Full Colored pages. It doesn't load the images and just displays "Error occurred while loading image". Already tried enabling "Canvas Based Rendering" but it didn't help.

**Comment by mienaiyami** [comment]
Is there any error when "Canvas Based Rendering" is disabled?  "Error occurred while loading image" is only showed when its enabled.
If possible, please send the average image resolution and size under.

**Comment by himouto** [comment]
Getting the error with "Canvas Based Rendering" enabled or disabled

**Comment by mienaiyami** [comment]
That would be weird because there is no error defied when "Canvas Based rendering" is disabled.
Can you show some screenshots, or screen recording if possible?
Also make sure the images are not corrupted by opening them inside an image viewer.

**Comment by himouto** [comment]
Not the same error, reader won't load the images if they're full colored for some reason

"Canvas Based Rendering" enabled:

![Screenshot 2024-02-04 132111](https://github.com/mienaiyami/yomikiru/assets/14362301/2ff47cfe-d041-45fd-947a-fa1daffe3224)

"Canvas Based Rendering" disabled:

![Screenshot 2024-02-04 132026](https://github.com/mienaiyami/yomikiru/assets/14362301/2ab7dd94-c01e-4868-9767-a2d3d77854cf)

Try to recreate it with any full colored manga/comics .cbz file with .png pages with at least 1400px horizontal resolution

**Comment by himouto** [comment]
These errors only occur with .cbz files - I cant recreate it with the folder extracted then dragged to the reader

**Comment by mienaiyami** [comment]
I will add option to use raw image data instead of filename to bypass this issue.
But not that it will greatly increase RAM and CPU usage.

**Comment by mienaiyami** [comment]
@zeoint Thats because most of the official cbz I encountered are designed like that, each page has whole manga name followed by page number, and if the manga name is too large then everything breaks.

**Comment by himouto** [comment]
> > I will add option to use raw image data instead of filename to bypass this issue. But not that it will greatly increase RAM and CPU usage.
> 
> The user above states that this error only occurs with archive and not with folders. So wouldn't just using the folder as chapters solve the issue. My thoughts.

Extracting all my cbz archives to folders just to use the reader would be hassle - also lose cover thumbnails, higher file size etc.

**Comment by himouto** [comment]
Any updates with the fix @mienaiyami ?

**Comment by himouto** [comment]
Thanks
