### ISSUE TITLE
About scroll speed

### ISSUE THREAD

**Issue by TyrantRC** [mienaiyami/yomikiru#356]
### Question

The reader has settings for "scroll speed" where there is a "Scroll A" and a "Scroll B" speed. What I want to know is what exactly this changes, and how to select which speed to use (Between A and B)

I tried changing the speed for each one to see if it changes the mouse scroll speed of pages in a manga but I didn't notice a change. So, what is this for?

**Comment by TyrantRC** [comment]
oh I see now, sorry I didn't notice the tooltip. Thank you @omodia.

Do you know if one can change the drag speed of the page? you know when you left-click the page and move the page up or down in the reader instead of using the scroll wheel or the scroll keys.

**Comment by mienaiyami** [comment]
> Do you know if one can change the drag speed/sensitivity of the page? you know when you left-click the page and move the page up or down in the reader instead of using the scroll wheel or the scroll keys.

That feature does not exist yet but will be added soon.
