### ISSUE TITLE
Letter and Word Spacing Values

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#361]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

epub

### Steps to reproduce

1. Open any epub.
2. Activate Word Spacing and Letter Spacing.
3. Change their values.

### ✔️ Expected Behavior

1. For the value boxes of **letter and word** spacing to be changed, ranging from 0 to n.nn.
2. And the value boxes of **letter and word** spacing to be more spacious as they would follow two digits after period and their current boxes are not legible.

### ❌ Actual Behavior

1. Increasing / decreasing the value causes it to go to minus somehow.
2. Box are not spacious.

https://github.com/mienaiyami/yomikiru/assets/116664905/9c8b7ab7-0a8d-4713-92a3-97978e4bce81

---

### Somehow its looping.

https://github.com/mienaiyami/yomikiru/assets/116664905/65770d5c-1214-455f-8108-75c95d8a312a

**Comment by mienaiyami** [comment]
> ### Some suggestions.
> 1. **Line height,**
> 
> * Minimum value = 1.
> * Value Range = 1 to n.
> * * Example = 1, 2, n.
> * Increments / Decrements of 1 when using arrows.
> * As 0 means, the lines of the same paragraph would merge forming a single line, making it unreadable.
> 
> 2. For **Paragraph** Spacing,
> 
> * Minimum value = 0.
> * Value Range = 0 to n.
> * * Example = 0, 1, 2, n.
> * Increments / Decrements of 1 when using arrows.

When setting the limits initially I did consider this same, but later i had to lower them a bit because it was needed.
Increment of 1 is too much in my opinion, after testing and using it for a long time of course.

And in word spacing 0.01 is too small.

**Comment by mienaiyami** [comment]
There have been cases when I needed word and letter spacing in negative, it totally depends on the font you use. While noone will need it as low as -1 but I have kept it there for specific cases.
