### ISSUE TITLE
Epub / Plain HTML, 4 Layout Option Looping and Unexpected Behaviors

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#362]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

epub

### Steps to reproduce

The 4 layout options in the reader are looping.

1. Open any epub / Plain HTML.
2. Enable line height, paragraph, word, and letter spacing. (You can also check them seperately, the result would be same.)

### ✔️ Expected Behavior

1. For the values to not loop.
2. **Line height** minimum value should be 1 only.
- As 0 means, the lines of the same paragraph would merge forming a single line, making it unreadable.

### ❌ Actual Behavior

1. Values loop.
2. Line height minmum value can be 0.

---

https://github.com/mienaiyami/yomikiru/assets/116664905/fd08d954-16f0-4a51-b6b1-2740779a998d

**Comment by mienaiyami** [comment]
Its probably all number input, after #313.
Will be merging it will #361 because related. If there are more additions, comment on #361.
