### ISSUE TITLE
Two Reserved Keys Do Not Show Warning Prompt

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#371]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

None

### Steps to reproduce

1. Open Yomikiru.
2. Go to shortcut keys.
3. Assign Esc And Tab to any shorcut key.
4. They can't be used as they are reserved keys, but assigning them doesn't show any prompt like it does for other reserved keys.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/f0a5c4af-84a3-4dfd-bca8-f3ebd162841f

### ✔️ Expected Behavior

For esc and tab to show warning prompts like other reserved keys when assigning.

### ❌ Actual Behavior

They both are not showing warning prompts when assigning.

**Comment by mienaiyami** [comment]
They are common navigation keys, used to navigate through page, it would be unreasonable to make a popup for them.
