### ISSUE TITLE
Any version after 2.19.2 will not load pages on Fedora 39

### ISSUE THREAD

**Issue by sorvani** [mienaiyami/yomikiru#376]
### Type of installation

build from git source with yarn

### Type of reader (if reader related)

None

### Steps to reproduce

Been running 2.19.2 with no issues. Updated to 2.19.5 from git and the application will launch fine, but there are no pages for any cbz. It simply shows the default icon for a failed to load image.

I reverted git to 2.19.4 (`git checkout 02eaca7`) and experienced the same issue. SO I switched back to 2.19.2 (`git checkout 75c0772`) and it works again.

I run this on Fedora 39. Normally, I build the executable with `yarn run package`. For testing I used `yarn start`

**Comment by mienaiyami** [comment]
I believe this issue will be in case of `yarn start` only. Images should be displaying in packaged application.

**Comment by sorvani** [comment]
yarn start works just fine with 2.19.2 and not with 2.19.5 so yeah that is not the problem.

**Comment by sorvani** [comment]
See another update today. It works again. Creating executable or not.
2.19.6 commit #96a31c3
yarn run package created a working executable.
yarn start also works just fine

**Comment by mienaiyami** [comment]
It was fixed in commit mentioned beside the "closed this" message above, maybe you missed it.

**Comment by sorvani** [comment]
Did not. Just replied from my phone the other day. Was back at my desk today and noticed the new version update and tested. thanks for the fix.
