### ISSUE TITLE
Have Option to Have Uniform Image Widths When Using Vertical Scroll

### ISSUE THREAD

**Issue by DTM9025** [mienaiyami/yomikiru#381]
### Type of reader (if reader related)

image

### Description of the new feature / enhancement

When using Yomikiru to read webtoons with Vertical Scroll reading mode, there are instances when the images are unaligned in their widths if the images are not the same aspect ratio or resolution, making the experience subpar. You can see this below, where the first "page" in the screenshot is 720 X 1000 while the second is 720 X 500.

![Screen1](https://github.com/mienaiyami/yomikiru/assets/11283512/26735d5d-236a-4a77-9386-78f92400abe9)

While there is an option to set a max image width, unless you play around to find the right size percentage that makes it work, it either is still wrongly sized or has a weird alignment problem as seen below.

![Screen2](https://github.com/mienaiyami/yomikiru/assets/11283512/ce56164d-a81c-44fe-a606-56d41d915147)

Again, if you play around you can get a setting the makes it work, but if you want to change the scaling, or change from a window size to another, or to fullscreen, etc., you'd have to find a max image width that would work with that scaling through trial and error.

![Screen3](https://github.com/mienaiyami/yomikiru/assets/11283512/f3560573-b7d1-400d-8b57-fafd0fdb5b9f)

An option or way to make the image widths uniform regardless of aspect ratio or resolution when doing vertical scrolling to allow resizing to be intuitive would be beneficial to the reading experience.

### Scenario when this would be used?

This would mainly be used for reading webtoons that, for one reason or another, have images that are differing in image aspect ratios and/or resolutions, and ensure that the intuitive setting of size works as expected when doing vertical scroll.

### Supporting information

See the screenshots in the first section.

**Comment by mienaiyami** [comment]
Uncheck this option at end on reader-settings. It is for manga/comic format that usually have double spread pages.
![image](https://github.com/mienaiyami/yomikiru/assets/84740082/a7a215a2-7d7f-4e22-8f32-ccdf734d7044)

**Comment by mienaiyami** [comment]
If the issue is not fixed, reopen it and provide more info.
