### ISSUE TITLE
Epub Progress

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#382]
### Type of installation

Portable (.zip)

### Type of reader (if reader related)

epub

### Steps to reproduce

1. Open any epub file.
2. Scroll down to 50% or any other%.

### ✔️ Expected Behavior

To start from the progress% recorded.

### ❌ Actual Behavior

The progress is recorded, but it starts from the top instead of the progress% recorded.

https://github.com/mienaiyami/yomikiru/assets/127277950/8dc25816-e5f5-4cc8-8468-622946d1ffa0

**Comment by mienaiyami** [comment]
Im redoing whole epub-reader because many old and new epub issues cant be fixed with current epub-reader, including performance issues.
So I will be closing it for now because maybe newer one might not have such issue.
I will soon provide a separate version in announcements for those who want to help test it.

**Comment by mienaiyami** [comment]
I won't be changing it into something else entirely. I only plan to redo the working of it behind the scene, so it is easier to manage and fix/add new feature. 


> A doubt. Is the redoing also applicable to the txt and xthml reader?

Can't say for sure now, but as you already know current epub-reader handles almost all epub smoothly now (with the "hide list" feature). I doubt there is even any use if it now, and it also made current epub reader unnecessary complex. 
I will decide what to do with this after Im done implementing new epub reader.

**Comment by mienaiyami** [comment]
Plus, I wont be building a fully compatible epub-reader, I will only do enough to support most web/light novel formats.
