### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#42]
### Description of the new feature / enhancement

Miscellaneous ideas.

### 1. Zen Mode to Zen Mode / Full Screen
- **To avoid confusion for [new users](https://github.com/mienaiyami/react-ts-offline-manga-reader/issues/34) to this app to know where full screen option is in shortcut keys.**

![1](https://user-images.githubusercontent.com/116664905/210405576-ea0052b5-ada5-411e-a8d0-32b1150f061f.png)

### 2. 
![2](https://user-images.githubusercontent.com/116664905/210405583-b6f26107-6a8d-46c3-9181-4623c1867b39.png)

### 3. 
![3](https://user-images.githubusercontent.com/116664905/210405587-fdf81ac7-6e2d-4cf2-8f9b-cbaa54efe36e.png)

### 4. UI Idea.
- **More Space after and before colon.**
- **More Space between Manga and Chapter.**
- **Border surrounding Manga and Chapter.**

![4](https://user-images.githubusercontent.com/116664905/210406476-0b408f8f-f32d-4d9f-918a-1b4fa2a7b509.png)

### Scenario when this would be used?

Normal Use.

**Comment by mienaiyami** [comment]
Thanks for the suggestion. I have changed them accordingly; you will see changes in next update.
If there is nothing more to add then close this issue.

**Comment by mienaiyami** [comment]
> I forgot the colon in a line in the previous UI idea.

I didn't get it, can you be more specific.
