### ISSUE TITLE
--topBar-hover-color

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#46]
### Steps to reproduce

1. Go to --topBar-hover-color and pick a color that is different from --body-bg.

### ✔️ Expected Behavior

Expecting the top bar color to change to chosen color in --topBar-hover-color.

### ❌ Actual Behavior

Top Bar color is not changing, but the home and settings button background color changed to the selected color.

**Comment by mienaiyami** [comment]
`--topBar-hover-color` is color which button change to when mouse is over them, thought this doesnt apply to system button anymore. `--topBar-color` is what you are looking for.

**Comment by mienaiyami** [comment]
Sorry for delaying release, I have been trying to improve performance. Update will be available soon.
This issue is hard to fix as it will disrupt custom themes users have made already, But I will try to fix to my best.
