### ISSUE TITLE
Bookmarks and History hover

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#47]
### Description of the new feature / enhancement

Hover over the history/bookmarked manga/chapter in home screen and you can see the name of manga, chapter, pages, date.
- Can you add the colon for both of them too as you did for [the reader](https://github.com/mienaiyami/react-ts-offline-manga-reader/issues/42#issuecomment-1371058440) for the upcoming update. Thank you.

![1](https://user-images.githubusercontent.com/116664905/212697780-00389314-29e6-41bb-9cf5-e3248c52d3d2.png)

**Comment by mienaiyami** [comment]
Fixed. Will be released in next update.
