### ISSUE TITLE
Audit Usage

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#55]
### Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
- A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
- To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
- Note that for performance reasons, only the first access to one of the properties is shown.
### AFFECTED RESOURCES
- index.js:1
- Learn more: User-Agent String Reduction

![image](https://user-images.githubusercontent.com/116664905/218245193-636a8007-1292-4682-8099-39bb8a71e36a.png)

**Comment by mienaiyami** [comment]
No, its totally fine. Besides, I'm not using any of these. It is probably the main library I'm using for making ui.

**Comment by mienaiyami** [comment]
I have fixed this but didn't release update since there have been multiple updates yesterday. I will release later today.
