### ISSUE TITLE
Add more types of Images support

### ISSUE THREAD

**Issue by josegb123** [mienaiyami/yomikiru#62]
### Description of the new feature / enhancement

I have a lot of mangas and they are in different formats like webp files. when i try to open these files the program say format not supported.

### Scenario when this would be used?

When i try to open webp image files

**Comment by mienaiyami** [comment]
WEBP files are supported. And many other image formats are supported as well like SVG, APNG, GIF, AVIF.
You are either on a very old version or your file maybe be corrupted.
Can you send some screenshots of error and image files in file explore so I can know the issue?

**Comment by mienaiyami** [comment]
WEBP files are supported. And many other image formats are supported as well like SVG, APNG, GIF, AVIF.
You are either on a very old version or your file maybe be corrupted.
Can you send some screenshots of error and image files in file explore so I can know the issue?

**Comment by josegb123** [comment]
[image: image_39.png][image: image_40.png][image: image_41.png]

**Comment by mienaiyami** [comment]
It seems like you replied to email notification directly. I didn't receive any images on neither email or github.

**Comment by mienaiyami** [comment]
Do you still have problem loading webp image? If not then close the issue otherwise reply to this on github or else I will be closing this issue in 2days

**Comment by mienaiyami** [comment]
I will be closing this issue, if you have any problems please let me know.
