### ISSUE TITLE
Home Page Blank Screen

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#64]
### Steps to reproduce

1. Open Yomikiru again after checking 'ask before closing window'.
2. After opening yomikiru, close it.
3. Dialogue box pops up, but the background will become black.
4. It remains black until restarted or ctrl+r.

- This only happens when manga reader is opened from the folder or without any manga. Only happens in homepage.

### ✔️ Expected Behavior

No blank screen.

### Blank screen.

![image](https://user-images.githubusercontent.com/116664905/219920830-f37fd7ca-d884-45a5-837c-cf42efa1eb0b.png)

**Comment by mienaiyami** [comment]
It was because of empty history. 
Fixed.
