### ISSUE TITLE
Better options for image fit

### ISSUE THREAD

**Issue by meidoqt** [mienaiyami/yomikiru#67]
### Description of the new feature / enhancement

Really liking this reader so far, just wishing it had better image fit options. My suggestion is to replace the current options with the following ones:

- Option to view image in 1:1 native res
- Option to Limit to Width, Height, or Both
- Option to Stretch Width, Height, or Both

Basically I'm describing the options on the cubari.moe online reader

**Comment by mienaiyami** [comment]
Thanks for suggestions. I will be working on them.

**Comment by mienaiyami** [comment]
> Option to view image in 1:1 native res

Can you explain this?
