### ISSUE TITLE
Unexpected behaviour after Entering/Exiting Zen Mode

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#71]
### Setup or portable version of the app?

Portable

### Steps to reproduce

1. Open any manga.
2. Scroll down a little bit in the same page and enter/exit zen mode.
3. It will enter/exit the zen mode at the starting of the current reading page.

### ✔️ Expected Behavior

To enter/exit zen mode at the same location.

### ❌ Actual Behavior

When entering/exiting zen mode the app starts at the starting of the current page.

**Comment by mienaiyami** [comment]
I had not experienced such bug.
Please check total page number or size of a single image. 
Usually in manhwa, images are very long and toggling zen mode focuses on start of current image.

**Comment by mienaiyami** [comment]
I have already fixed the issue but will be released when other changes to app are stable.

**Comment by mienaiyami** [comment]
I remembered while testing that this was added because when window in not maximized (not taking full screen size) then entering/exiting zen mode will take you to random page.
