### ISSUE TITLE
Natural sorting for chapter lists

### ISSUE THREAD

**Issue by CaptainLingonberry** [mienaiyami/yomikiru#72]
### Description of the new feature / enhancement

As it stands, chapters are sorted alphabetically in the side list. One problem with this is the way extra/omake chapters are commonly numbered
 
Extra chapters end up being sorted before the main chapter:
Vol. 5 Ch. 41.cbz
Vol. 5 Ch. 42.5.cbz
Vol. 5 Ch. 42.cbz
Vol. 5 Ch. 43.cbz

An option for [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) would fix this:
Vol. 5 Ch. 41.cbz
Vol. 5 Ch. 42.cbz
Vol. 5 Ch. 42.5.cbz
Vol. 5 Ch. 43.cbz

**Comment by mienaiyami** [comment]
It is using standard natural sorting not alphabetical.
If it was alphabetical, chapter list would have been like.
 - Chapter 1
 - Chapter 10
 - Chapter 11
 - Chapter 12
 ...
 - Chapter 20
 - Chapter 21
  ...

And extra chapters are being sorted after main
![image](https://user-images.githubusercontent.com/84740082/221102192-87781c94-9949-4a43-8ea4-d5abb94042aa.png) ![image](https://user-images.githubusercontent.com/84740082/221103089-7c4bc583-30fc-464c-bb3d-4fb30ef22910.png)


But unfortunately, it doesn't work with file formats. It's just how the algorithm works. Even if you look in file explorer, you will find they are not sorted properly.
Though I do have some ways, but it depends on displaying different file name. I will try to make it work without affecting that.

**Comment by CaptainLingonberry** [comment]
Ah, I've been using cbz archives for a long time because of html-mangareader, I didn't realize to try folders. Now that I'm mainly using your app, I could just switch to using folders in case it doesn't work out with natural sorting files.

**Comment by mienaiyami** [comment]
I have fixed the issue, but update will be released later because of some other changes.
