### ISSUE TITLE
Theme Maker Bugs

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#75]
### 1. --icon-color
- 'Link' is linked to --font-color instead of --icon-color.
- Some fonts are changing when using --icon-color. The fonts should be linked to --font-color.

![2](https://user-images.githubusercontent.com/116664905/222039984-71cbf12c-0bbb-4a38-b135-4f36973bf923.png)
![--icon-color](https://user-images.githubusercontent.com/116664905/222036610-cc0d1134-ae71-4c80-bfbc-9662216552af.png)
![2](https://user-images.githubusercontent.com/116664905/222039984-71cbf12c-0bbb-4a38-b135-4f36973bf923.png)

**Comment by mienaiyami** [comment]
I actually need to redo whole theme system as it wasnt in mind to make it customizable when i started
