### ISSUE TITLE
.EPUB Support

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#78]
### Description of the new feature / enhancement

To Read novels.

**Comment by mienaiyami** [comment]
Thanks for enhancement request.
I have had this in plans but its totally different from displaying images. Even if I'm able to make it well it won't be as good as other epub like there like Freda, which provides too many settings just for epub.

I will be working on it but might take a long time.

**Comment by mienaiyami** [comment]
@omodia Thanks

> Will this affect RAM usage?

It might but not any noticeable amount. epub format is not supported on web so I will have to use some other tool to read its data and display it. 

You can expect this feature and other issues in about a month as Im busy right now.

**Comment by mienaiyami** [comment]
Yes, Im currently working on #75. And you can expect it in few days but might have some bugs because I cant test everything, so please report any you encounter.

**Comment by mienaiyami** [comment]
Sorry but i have tried my best to get a good epub reader in app but cant seem to do it, as of now at least. I will keep trying and learn mre about epub format.

You can try my personal favorite app "Freda" which is available on Microsoft store for free. It has all the necessary features needed for a comfortable read.

**Comment by mienaiyami** [comment]
Thanks, I will try my best to implement epub in it.
