### ISSUE TITLE
Screen Disable In Vertical Scroll Reading Mode

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#81]
### Setup or portable version of the app?

Portable

### Steps to reproduce

Go to next / previous chapter by using mouse click on the right / left part of the image.

https://user-images.githubusercontent.com/116664905/228540014-535ffdac-d44e-4d37-a53a-c93de2470479.mp4

### ✔️ Expected Behavior

To not show the screen in vertical scrolling mode.

### ❌ Actual Behavior

Shows the screen.

**Comment by mienaiyami** [comment]
I tried it on both setup and portable version and couldn't find any issue, please try restarting app, or share more information.

**Comment by mienaiyami** [comment]
As a general question, does all settings reset when you install new version in portable version? As it is not indented.
