### ISSUE TITLE
Theme maker bugs

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#82]
### Text Color And Icon Color
- These both are not linked properly in reader settings.
- Size, pages per row, reading mode, scroll a, px, etc. These are linked to Icon Color instead of Text Color.
- 1:1 is linked to text color instead of icon color.

![Text Colour](https://user-images.githubusercontent.com/116664905/228535533-5b9e2c2a-f0d1-4f4c-b1c2-33524acaa9ab.png)

### List Item BG Color
- This is at two places with the same name.

### Body BG Color
- Not Working properly.

https://user-images.githubusercontent.com/116664905/228539473-302862de-bf4b-4873-91bc-574eb85f50fc.mp4

**Comment by mienaiyami** [comment]
> Body BG Color

Some changes require refresh of app but I will try to make it so changes reflect without refresh.

> Text Color And Icon Color

Thank you for pointing out the issue, I will immediately fix it.

**Comment by mienaiyami** [comment]
> In v2.9.2 the dragging of color changing button in theme system is late / clunky as compared to v2.9.0. 

You can only have one thing, either colors apply without refresh or this clunky system.
I think tis clunkiness wont matter since no one change theme everyday.
