### ISSUE TITLE
History

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#86]
### Setup or portable version of the app?

Portable

### Steps to reproduce

- Open any manga.
- Close it and open another chapter or manga.

### ✔️ Expected Behavior

- Explained in [#69 and below comments.](https://github.com/mienaiyami/yomikiru/issues/69#issuecomment-1439645935)
- To record all read chapters.
- And latest read chapters at the top.
- And manga, chapter titles to respect margins.

### ❌ Actual Behavior

- Only records latest record and deletes the previous record. 
- Clips through the margins.

https://user-images.githubusercontent.com/116664905/228768769-3ad10d0a-615c-450b-be44-98ed978b0f5a.mp4

**Comment by mienaiyami** [comment]
> Only records latest record and deletes the previous record.

Thats because there's a option to disable chapter recording. #74
