### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#87]
### Setup or portable version of the app?

Portable

### Steps to reproduce

I have used the maximum word limit possible for both chapters and manga titles in the test file.

- Open any manga and chapter that have long titles.
- Or open the test file - [TESTTE~1.ZIP](https://github.com/mienaiyami/yomikiru/files/11109261/TESTTE.1.ZIP).

### ✔️ Expected Behavior

- Manga: Title to start after Manga: not from the bottom.
- Manga, chapter titles to not clip through the margin and on to the reader.

### ❌ Actual Behavior

- Manga title is not aligned to Manga: but instead starts from the bottom.
- Manga title and chapter title clips through the margins.

https://user-images.githubusercontent.com/116664905/228771110-4929eb7c-70c6-4b3e-8718-f9b11830fb95.mp4

**Comment by mienaiyami** [comment]
The zip file you sent is invalid

**Comment by mienaiyami** [comment]
Fixed.

**Comment by mienaiyami** [comment]
There is some alignment issue, that will is fixed but will be released later.
