### ISSUE TITLE
Setup misbehavior

### ISSUE THREAD

**Issue by GenoXu** [mienaiyami/yomikiru#89]
### Setup or portable version of the app?

Setup

### Steps to reproduce

https://user-images.githubusercontent.com/31614025/230069266-c34c384f-da17-42f8-895a-7e910478854f.mp4

**Comment by mienaiyami** [comment]
Did you install it before? It seem that app has been deleted and files does not exist anymore. It can happen if you close setup in middle of installing or some antivirus software deleted it, please check.

**Comment by mienaiyami** [comment]
Try deleting the shortcut then installing app again,

**Comment by GenoXu** [comment]
I moved the folder from `AppData` to `Program Files`, then manually create the shortcut and now it works. 
![image](https://user-images.githubusercontent.com/31614025/230101765-5250e475-9e3e-46e6-bc2f-e1d8ca7636dd.png)
