### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost** [mienaiyami/yomikiru#9]
- Option to show images in their 'original size' in the reader menu of manga reader.

By the way I created a listing of your application in [alternativeto.net](https://alternativeto.net/software/react-ts-offline-manga-reader/about/).

**Comment by mienaiyami** [comment]
Thank you very much for creating a listing of my application. I have been busy for some days, but I will make sure to upload update with custom theme by Sunday. And about the "original size", you might have to compromise ability to zoom but I will try to make it work.

**Comment by mienaiyami** [comment]
Thank you, I will try to implement original size in next update.
Hope you like custom theme maker. Don't hesitate to report bugs and issues.

**Comment by mienaiyami** [comment]
I tried working on it many times but can't do it quite right because everything doesn't fit together with whole app. 
If this feature is not that necessary you can close it, otherwise keep it open and provide some more info about this feature, I will try to make if I can.
