### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by omodia** [mienaiyami/yomikiru#91]
### In this video, for example, 

- After opening a chapter the RAM usage is 90 - 100 MB. You can see the CPU usage going down.
- If a chapter is opened before the CPU usage goes down the RAM usage increases.
- This also happens if you start scrolling down before the CPU usage goes down.
- After going through 6 chapters and coming back to the starting chapter the RAM usage is 150 MB and it stays there.
- It will again increase after opening another chapter and so on until the application is refreshed.
### Is it because there is some residual cache of previous chpaters remaining or something like that?

**Comment by mienaiyami** [comment]
> Is it because there is some residual cache of previous chapters remaining or something like that?

Likely but i don't know myself yet. It can be the app still loading images after new chapter is opened, I will look into it

**Comment by mienaiyami** [comment]
I havent had time to do so due to some reasons.

**Comment by mienaiyami** [comment]
I have checked many blogs and posts about memory issue and it seems there is no solution as or now, other than refreshing, to clear up memory. I can only try to clear memory but it doesnt always work (mostly in case of large amount of images. 
I have put every way to clear memory and there is nothing more provided by the framework.
