### ISSUE TITLE
Page Spacing

### ISSUE THREAD

**Issue by l9tr** [mienaiyami/yomikiru#92]
### Description of the new feature / enhancement

Option to decrease page spacing to zero.

### Scenario when this would be used?

For continuous, scroll-like images, like in manhuas and manhwas.

**Comment by mienaiyami** [comment]
Try unchecking this 
![image](https://user-images.githubusercontent.com/84740082/232585979-46774358-6ebb-4a90-bc37-c6971fdac5bb.png)

**Comment by mienaiyami** [comment]
Close issue if resolved.

**Comment by l9tr** [comment]
Oh, I see. My screen wasn't big enough, so I had to scale down the UI for the Other Settings to appear. Thanks.

**Comment by mienaiyami** [comment]
You can also scroll reader settings it its out of screen.
