### ISSUE TITLE
Screen Brightness Adjuster

### ISSUE THREAD

**Issue by euryyydice** [mienaiyami/yomikiru#93]
### Description of the new feature / enhancement

Designed to help control the brightness of your computer screen, monitor or display while reading. 

### Scenario when this would be used?

The primary purpose of a screen dimmer is to reduce eye strain, particularly when working in low light conditions or during prolonged periods of screen use.

### Supporting information
This is a similar feature from tachiyomi where u can dim the screen cause it is too bright. 
![image](https://user-images.githubusercontent.com/131165429/232955379-a680a8b9-62ff-4ced-9d92-b9c0d183e4af.png)
![image](https://user-images.githubusercontent.com/131165429/232955415-e9876419-7f72-42c2-9615-b7d7b21ed4d1.png)

_No response_

**Comment by euryyydice** [comment]
> I apologize if I'm wrong, but Isn't that a windows os setting, how is it linked to a reader? You can manually adjust the screen brightness. If you are using windows 10 /11 you can also turn on night light to reduce eye strain.

oh im sorry for this cause i thought this feature could also be added. I use tachiyomi in my phone and it has an in built screen dimmer while reading. I can actually manually adjust the screen brightness but the lowest brightness in my pc is still too bright for me, I just wish we would be able to dim the screen more.

**Comment by mienaiyami** [comment]
Let me know if there is some error/bug in this.
